### ISSUE TITLE
Generating examples in documentation seems outdated

### ISSUE THREAD

**Issue by corroded** [Compass/compass#1020]
I am following [this page](https://github.com/chriseppstein/compass/blob/stable/doc-src/README.markdown):

and it seems that it is a bit outdated. Doing this line 

```
./bin/thor generate:example blueprint/grid/simple/
```

generates an error:

```

Generating /examples/blueprint/grid/simple/
DIRECTORY content/examples/blueprint/grid/simple/
   CREATE content/examples/blueprint/grid/simple.haml
/Users/eumir/Projects/compass/doc-src/tasks/generators.thor:22:in `block in example': undefined method `capitalize' for nil:NilClass (NoMethodError)
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:35:in `open'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/1.9.1/open-uri.rb:35:in `open'
    from /Users/eumir/Projects/compass/doc-src/tasks/generators.thor:18:in `example'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/runner.rb:34:in `method_missing'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:108:in `run'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/eumir/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/bin/thor:6:in `<top (required)>'
    from ./bin/thor:16:in `load'
    from ./bin/thor:16:in `<main>'
```

Looking into the code, I tried looking at line 22 and added an `if options[:framework].capitalize` clause, but now it keeps saying it is not a valid framework. I'm not sure I understand what the valid framework parameters are but I tried 'CSS3' and 'Compass' and they didn't work. 

I'll gladly update this given I am pointed to the right direction(since I am already updating the docs anyway).

If we could also just specify the files needed for this to work, that would be great as well. I can just copy off the other examples(but right now just copying the example file throws an error:)

```

NoMethodError at /reference/compass/css3/selection/
undefined method `reps' for nil:NilClass

Ruby    lib/examples.rb: in example_haml, line 3
Web GET localhost/reference/compass/css3/selection/
```

**Comment by corroded** [comment]
Seems like I just needed to add --framework Compass to make it work. My bad.
