### ISSUE TITLE
0.13.alpha.2 watch broken on OSX with RVM

### ISSUE THREAD

**Issue by bez4pieci** [Compass/compass#1243]
compile works, but watch is broken.
here's the output:

```
$ compass watch --trace
ArgumentError on line ["465"] of /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/pathname.rb: different prefix: "/" and "."
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:55:in `block in create_sass_watchers'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in `map'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:51:in `create_sass_watchers'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/watcher/project_watcher.rb:25:in `initialize'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `new'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/commands/watch_project.rb:64:in `perform'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/commands/base.rb:18:in `execute'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/bin/compass:30:in `block in <top (required)>'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/bin/compass:44:in `call'
  /Users/dre/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.13.alpha.2/bin/compass:44:in `<top (required)>'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/bin/compass:19:in `load'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/bin/compass:19:in `<main>'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
  /Users/XXX/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

Environment:

OSX

```
 - RUBYGEMS VERSION: 1.8.25
 - RUBY VERSION: 1.9.3 (2013-02-22 patchlevel 392) [x86_64-darwin12.3.0]
```

```
rvm 1.19.1 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by scottdavis** [comment]
This is not "broken" its just an exception because you are setting paths wrong. Can you post your compass config

**Comment by bez4pieci** [comment]
the same config works with 0.13.alpha.0

``` ruby
require 'susy'
require 'ceaser-easing'
require 'compass-normalize'
require 'compass_twitter_bootstrap'

http_path = "/"
project_path = "./"

sass_dir = "meta/sass"
css_dir = "src/static/css"

images_dir = "src/static/images"
javascripts_dir = "src/static/js"
fonts_dir = "src/static/fonts"

http_stylesheets_path = "/static/css"
http_images_path = "/static/images"
http_generated_images_path = "/static/images"
http_javascripts_path = "/static/js"
http_fonts_path = "/static/fonts"

sprite_load_path = [ "./meta/sprites" ]

Encoding.default_external = 'utf-8'
Encoding.default_internal = 'utf-8'

output_style = :compact
line_comments = false
```

**Comment by scottdavis** [comment]
remove `project_path = "./"` its not needed. See if that fixes the problem since the project path will always be where the config file is unless you define other wise.

**Comment by bez4pieci** [comment]
It worked! Thanx!

**Comment by scottdavis** [comment]
ok i know what the problem was ill get it fixed

**Comment by alademann** [comment]
I'm seeing this issue on 0.13.alpha.4 with the following config.rb 

``` ruby
  sass_dir          = "sass"
  http_path         = "static"
  css_dir           = "#{http_path}/assets/css"
  fonts_dir         = "#{http_path}/assets/fonts"
  images_dir        = "#{http_path}/assets/img"
  javascripts_dir   = "#{http_path}/assets/js"

  output_style      = :expanded
  line_comments = true

  relative_assets = true

  asset_cache_buster :none
```

**Comment by scottdavis** [comment]
@alademann what error are you getting?

**Comment by chriseppstein** [comment]
closing. please reopen with details if this is still happening.
