### ISSUE TITLE
required extension from an extension in extensions_dir does not get recognized

### ISSUE THREAD

**Issue by krisbulman** [Compass/compass#1279]
When adding an extension that requires another extension, compass does not pick up the other required extension in the `extensions_dir` (or extensions/ if that is not set).

The docs say:

```
The standard location for extensions is project_root/extensions for stand-alone projects and project_root/vendor
/plugins/compass_extensions for rails projects. Additionally, the user may customize their extensions directory by 
setting extensions_dir in their compass configuration file.

To install into an existing project, simply place the extension into a project's extension directory. This could be done 
via a git clone or by extracting an archive. The name of the directory it creates should be the name of the extension. 
The project will now have access to the extension.
```
## example setup

Note: modular-scale requires sassy-math in it's [modular-scale.rb](https://github.com/Team-Sass/modular-scale/blob/master/lib/modular-scale.rb)

**config.rb** (no require set here)

```
  extensions_dir  = "sass-extensions"
  relative_assets = true
```

**sass-extensions/**

```
modular-scale/
sassy-math/
```

**style.scss**

```
@import "compass";
@import "modular-scale";
```

**compass compile**

```
$ ~/code/myproject (master *): compass compile --trace
LoadError on line ["45"] of /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb: cannot load such file -- sassy-math
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
  /Users/myusername/code/myproject/sass-extensions/modular-scale/lib/modular-scale.rb:2:in `<top (required)>'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:75:in `block in register_directory'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:39:in `detect_registration'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:74:in `register_directory'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:63:in `block in discover'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:62:in `each'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/frameworks.rb:62:in `discover'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/configuration/helpers.rb:120:in `discover_extensions!'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/commands/project_base.rb:27:in `configure!'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/commands/update_project.rb:37:in `initialize'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/bin/compass:30:in `block in <top (required)>'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/bin/compass:44:in `call'
  /Users/myusername/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.4/bin/compass:44:in `<top (required)>'
  /Users/myusername/.rbenv/versions/1.9.3-p194/bin/compass:23:in `load'
  /Users/myusername/.rbenv/versions/1.9.3-p194/bin/compass:23:in `<main>'
```

**Comment by scottdavis** [comment]
So I'm adding the top level directories of the extensions folders to the ruby load path which should solve this problem ex:

```
[sdavis@Hurr:compass-test]$ bundle exec irb -rcompass
2.0.0-p195 :001 > $:
 => ["/Users/sdavis/Work/compass/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/sass-3.3.0.alpha.354/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/listen-1.1.6/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/rb-kqueue-0.2.0/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/rb-inotify-0.9.2/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/ffi-1.9.0/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/ffi-1.9.0/ext/ffi_c", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/rb-fsevent-0.9.3/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/chunky_png-1.2.8/lib", "/Users/sdavis/.rvm/gems/ruby-2.0.0-p195/gems/bundler-1.3.5/lib", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby/2.0.0/x86_64-darwin12.3.0", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/site_ruby", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/vendor_ruby/2.0.0", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin12.3.0", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/vendor_ruby", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0", "/Users/sdavis/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/x86_64-darwin12.3.0", "/Users/sdavis/.compass/extensions/blah", "/Users/sdavis/Work/compass-test/extensions/foobar", "/Users/sdavis/Work/compass-test/extensions/foobar/lib"]
```

notice the last 3 elements in the array

**Comment by scottdavis** [comment]
@krisbulman try this branch https://github.com/chriseppstein/compass/tree/extension_load_paths and see if it suites this use case

**Comment by krisbulman** [comment]
Switched to the _extension_load_paths_ branch and ran from source, and ran it with the initial configuration. It failed again with the same error. 

BUT to test I tried unpacking modular-scale to the directory without specifying the root name and it worked.. so the primary unpacked gem must retain the version number to work.

example: 

**sass-extensions/**  

```
modular-scale-1.0.6
sassy-math
```

Then, if I switch back to the base names and recompile

**sass-extensions/**  

```
modular-scale
sassy-math
```

I get the original error of not being able to find sassy-math. 

I've tested this in both 'Compass 0.13.alpha.4' (release) and the _extension_load_paths_ branch with the same results.

**Comment by scottdavis** [comment]
Can you make a small repo that causes this error I think there maybe an error in your require. It should work like ruby gems where you require the ruby file from the extensions lib  folder.

**Comment by krisbulman** [comment]
@scottdavis  https://github.com/krisbulman/compass-1279

**Comment by krisbulman** [comment]
@scottdavis I wasn't aware it also needed to be required from the extensions folder, i'll try that... 

**EDIT** no dice. let me know if you see anything obvious

**NOTE** renaming modular-scale/ to modular-scale-1.0.6/ works

**Comment by scottdavis** [comment]
@krisbulman Ive pushed more changes to the extension_load_paths branch my test case is passing and your example works fine for me. I'm going to close this and merge in the changes to master.

**Comment by scottdavis** [comment]
Actually I found a race condition so this isn't ready yet

**Comment by scottdavis** [comment]
so if you add this to the top of your config file using that test project you posted everything should work.

``` ruby
# Require any additional compass plugins here.
load 'modular-scale'
```

**Comment by scottdavis** [comment]
@krisbulman can you try this again? and verify

**Comment by scottdavis** [comment]
ping @krisbulman can you give this a spin and verify that it works then ill update the docs

**Comment by chriseppstein** [comment]
I think this is fixed now. Please test against the latest prerelease (1.0.0.alpha.17 or greater)
