### ISSUE TITLE
Compile tries read directories above Project Directory.

### ISSUE THREAD

**Issue by roydukkey** [Compass/compass#1305]
The following command is run under a limited account. 

```
G:\Google Drive\GitHub\Compass Test\Site\Web\>
compass compile "sass/base/custom.sass" --trace --css-dir "data/compass"
```

Project Directory: `G:\Google Drive\GitHub\Compass Test\Site\Web\` (R)
--css-dir: `G:\Google Drive\GitHub\Compass Test\Site\Web\data\compass\` (RWD)
All permissions above the Project Directory are denied.

```
Errno::EEXIST on line ["245"] of C: File exists - G:/Google Drive/GitHub
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `each'
  C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/actions.rb:28:in `directory'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/compiler.rb:97:in `block in run'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/compiler.rb:97:in `each'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/compiler.rb:97:in `run'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/update_project.rb:45:in `perform'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:44:in `call'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  C:/Ruby200-x64/bin/compass:23:in `load'
  C:/Ruby200-x64/bin/compass:23:in `<main>'
```

If seems the command is failing when trying to read or make directories above the Project Directory. Why should it even be trying?

**The following senarios resolve the error**
- Giving full permission to the account above the Project Directory to the root.
- Creating the --sass-dir in the --css-dir before executing compile command (ie. 'data\compass\sass').

**Comment by roydukkey** [comment]
This only seems to be an issue when the file is in a folder two levels deeper than the sass_dir.

**Comment by roydukkey** [comment]
Okay. I think I've found the problem. It seems the [`Compass.Actions.directory`](https://github.com/chriseppstein/compass/blob/stable/lib/compass/actions.rb#L21-L34) is a little too greedy.

If any of the the directories don't exist the `FileUtils.mkdir_p` tries to make every single directory in the path variable its giving. The problem occurs when the commanding user identity doesn't have access above the Project Directory.

Hence, if the Project Directory is `\Web\` and the variable for `mkdir_p` is `G:\Google Drive\GitHub\Dado.Compass\Web\stylesheets\`, the process will think `Dado.Compass`, `GitHub`, etc. don't exist, because it doesn't have read access.

**To solve the issue, why not pass a path with a base of the location from which the command was called?** I'm not confident in my ruby skills, but this might be a step in the right direction. I'm not sure if `basename(dir)` gets the Project Directory or the command call path.

```
-     FileUtils.mkdir_p(dir) unless options[:dry_run]
+     FileUtils.mkdir_p(separate("#{basename(dir)}/")) unless options[:dry_run]
```

I feel this is a suitable solution, because we can expect the directories above the command call location to exist; since the call couldn't have been made otherwise.

**Comment by roydukkey** [comment]
This is the current error message for v1.0.1.

```
compass compile "theme/default/style/custom.sass" --trace --debug-info --css-dir "data/compass"

directory data/compass/theme/default/style
Errno::EEXIST on line ["247"] of C: File exists - C:/Users/roydukkey/Desktop
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:205:in `each'
    C:/Ruby193/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:477:in `update_stylesheet'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:209:in `each'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/sass_compiler.rb:40:in `compile!'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/update_project.rb:49:in `perform'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `call'
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
    C:/Ruby193/bin/compass:23:in `load'
    C:/Ruby193/bin/compass:23:in `<main>'
```

The error is still resulting form the same issue as stated previously. The solution is to make the file locations relative to the calling location. This needs to be done because we cannot assumed that the process has permissions above that directory.

Changes should be made at line 39 to 41 in [/cli/lib/compass/sass_compiler.rb](https://github.com/Compass/compass/blob/stable/cli/lib/compass/sass_compiler.rb#L39-L41).

```
def compile!
    process_relative_files = []
    individual_files.each { |file|
        process_relative_files.push([separate("#{basename(file[0])}") , separate("#{basename(file[1])}")])
    }
    @compiler.update_stylesheets(process_relative_files)
end
```
