### ISSUE TITLE
Error run compass watch

### ISSUE THREAD

**Issue by Lisaj** [Compass/compass#1329]
Encoding::CompatibilityError on line ["193"] of C: incompatible encoding regexp match (Windows-1250 regexp with ASCII-8B
IT string)
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/directory_record.rb:193:in 'relative_to_base'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/directory_record.rb:135:in 'ignored?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/directory_record.rb:328:in 'block in important_paths'
  C:/Ruby193/lib/ruby/1.9.1/find.rb:41:in 'block in find'
  C:/Ruby193/lib/ruby/1.9.1/find.rb:40:in 'catch'
  C:/Ruby193/lib/ruby/1.9.1/find.rb:40:in 'find'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/directory_record.rb:322:in 'important_paths'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/directory_record.rb:158:in 'build'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-0.7.3/lib/listen/listener.rb:46:in 'block in start'

**Comment by Lisaj** [comment]
I have instaled later compass beta

**Comment by scottdavis** [comment]
and? did that fix this?

**Comment by Lisaj** [comment]
No. My English is not the best. Here I wanted to tell what version I have installed.

**Comment by Lisaj** [comment]
Hello,
problem does the character "á" in the directory name. After removing the character watch works.
