### ISSUE TITLE
undefined method `options='

### ISSUE THREAD

**Issue by stephenway** [Compass/compass#134]
NoMethodError on line 88 of /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/script/parser.rb: undefined method `options=' for nil:NilClass

Happens after compiling my blueprint project which I did convert to the new Sass3/Compass 0.10 syntax.

Here's the full trace

```
   exists stylesheets
unchanged src/ie.sass
unchanged src/print.sass
  compile src/screen.sass
NoMethodError on line 88 of /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/script/parser.rb: undefined method `options=' for nil:NilClass
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/script/parser.rb:88:in `each'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/script/parser.rb:88:in `parse_mixin_include_arglist'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:584:in `parse_mixin_include'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:395:in `parse_line'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:286:in `build_tree'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:305:in `append_children'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:304:in `each'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:304:in `append_children'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:295:in `build_tree'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:288:in `each'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:288:in `build_tree'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:305:in `append_children'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:304:in `each'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:304:in `append_children'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:182:in `_to_tree'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:169:in `to_tree'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/files.rb:42:in `tree_for'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/import_node.rb:73:in `perform!'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:301:in `_perform'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/import_node.rb:64:in `_perform'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:209:in `perform'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/root_node.rb:37:in `perform'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `perform_children'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `map'
  /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `perform_children'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/import_node.rb:76:in `perform!'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:301:in `_perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/import_node.rb:64:in `_perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:209:in `perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/root_node.rb:37:in `perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `perform_children'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `map'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:322:in `perform_children'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:313:in `perform!'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/root_node.rb:59:in `perform!'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:301:in `_perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/node.rb:209:in `perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/root_node.rb:37:in `perform'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/tree/root_node.rb:29:in `render'
 /Users/user_name/.gem/ruby/1.8/gems/haml-3.0.1/lib/sass/engine.rb:159:in `render'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:103:in `compile'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/logger.rb:43:in `red'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:102:in `compile'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:93:in `compile_if_required'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:84:in `run'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:82:in `each'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/compiler.rb:82:in `run'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/commands/update_project.rb:33:in `perform'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/commands/base.rb:18:in `execute'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/commands/project_base.rb:19:in `execute'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/exec/switch_ui.rb:170:in `do_command'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/exec/switch_ui.rb:35:in `perform!'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/lib/compass/exec/switch_ui.rb:18:in `run!'
 /Users/user_name/.gem/ruby/1.8/gems/compass-0.10.0/bin/compass:26
 /usr/bin/compass:19:in `load'
 /usr/bin/compass:19
```

**Comment by nex3** [comment]
What's the Sass or SCSS that's causing this error?

**Comment by nex3** [comment]
Never mind. nex3/haml@c559c550a6a9fd3d05ff11a50fb0d8e53fd314f0 should fix this.

**Comment by stephenway** [comment]
Thank you, fixed my problem!
