### ISSUE TITLE
Rails unable to boot with Compass 0.10.0, Haml 3.0.3, Rails 3.0.0beta3

### ISSUE THREAD

**Issue by airhorns** [Compass/compass#137]
I updated to Haml 3.0.3 this morning, and none of the Rails commands work for me with this error: 

```
/Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/haml-3.0.3/lib/haml/util.rb:268:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/haml-3.0.3/lib/sass/plugin/rails.rb:4:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/haml-3.0.3/lib/sass/plugin.rb:268:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/haml-3.0.3/lib/sass/plugin.rb:268:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches/stylesheet_updating.rb:1:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches/stylesheet_updating.rb:1:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches.rb:2:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions.rb:5:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass/sass_extensions.rb:5:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass.rb:5:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass.rb:5:in `block in <top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass.rb:4:in `each'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/compass-0.10.0/lib/compass.rb:4:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:46:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:46:in `block (2 levels) in require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:41:in `each'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:41:in `block in require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:40:in `each'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler/runtime.rb:40:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/bundler-0.9.25/lib/bundler.rb:89:in `gem_require'
    from /Users/hornairs/Sites/dowling/config/application.rb:9:in `<top (required)>'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.0.beta3/lib/rails/commands.rb:39:in `require'
    from /Users/hornairs/.rvm/gems/ruby-1.9.2-head@rails3/gems/railties-3.0.0.beta3/lib/rails/commands.rb:39:in `<top (required)>'
    from script/rails:10:in `require'
    from script/rails:10:in `<main>'
```

It looks like when Compass goes to monkey patch the Sass plugin API, Sass::Plugin inclues Haml::Util which in turn does the defined?(Rails.root) check, throwing the error. Was that check not there in Haml v3.0.2? Can we move the Sass Plugin extension to the Compass.configure_sass_plugin! call?

**Comment by nex3** [comment]
This is almost certainly because Compass is loading Sass before Rails is fully loaded. [This is how I work around the issue in Sass](http://github.com/nex3/haml/blob/master/lib/haml/railtie.rb#L9-19).

**Comment by chriseppstein** [comment]
Can you set compass to :require => false in your Gemfile and see if that clears this issue up for you?

**Comment by nex3** [comment]
Get rid of some dead code that was breaking Rails 3. Closed by 6ad50ea2d8762c610f26920e268b732ad1010ae2.

**Comment by nex3** [comment]
Just FYI, `:require => false` does make the issue go away, but the above patch will make it work even without that.

**Comment by omarvelous** [comment]
Yea, no luck with Compass 0.10.1 and Haml 3.0.4

**Comment by omarvelous** [comment]
Seems to have been a Hassel error.... same require => false works... Sorry
