### ISSUE TITLE
LoadError on line ["55"] of C: cannot load such file -- wdm

### ISSUE THREAD

**Issue by Frikki** [Compass/compass#1410]
After installing compass on Windows 7 using

```
gem install compass -v '0.13.alpha.7'
```

running

```
compass watch --trace
```

produces

LoadError on line ["55"] of C: cannot load such file -- wdm
  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:199:in`load_dependent_adapter'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapters/windows.rb:33:in `load_dependent_adapter'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:190:in`usable?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapters/windows.rb:25:in `usable?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:182:in`usable_and_works?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:49:in `block in select_and_initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:47:in`each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `select_and_initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:272:in`initialize_adapter'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:264:in `setup'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/listen-1.1.6/lib/listen/listener.rb:64:in`start!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/watcher/project_watcher.rb:31:in `watch!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/commands/watch_project.rb:48:in`perform'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/commands/project_base.rb:19:in`execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/bin/compass:30:in `block in <top (required)>'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/bin/compass:44:in`call'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-0.13.alpha.7/bin/compass:44:in `<top (required)>'
  C:/Ruby193/bin/compass:23:in`load'
  C:/Ruby193/bin/compass:23:in `<main>'

**Comment by stevenw00** [comment]
Just run `gem install wdm`

**Comment by RaphaelDDL** [comment]
Isn't possible to make it a required gem (like sass is) only if you are on Windows (since `wdm` is win-only)?
Every win computer I install sass/compass gets this error (that would've been avoided some lost minutes/hours depending if I remind of having to install it). But oh well, don't know if is possible to set requirements based on platform.

**Comment by srsgores** [comment]
https://github.com/chriseppstein/compass/issues/1470

**Comment by Snugug** [comment]
I've just had a user run into this issue as well with Team-Sass/generator-style-prototype#46

Having this gem be a dependency on Windows systems would greatly ease Windows onboarding confusion

**Comment by scottdavis** [comment]
since we are moving away from having our own watcher in the 1.0 land and using sasses it may make sense to test and make sure you don't have issues with this using sass 3.3 watcher

**Comment by ameshkin** [comment]
I just do'nt understand what's happening. Ive tried things others have said is working for htem. Only on this mac, I just can't get compass working

Here is a stacktrace

LoadError on line ["55"] of /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- rgbapng
  /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-core-1.0.3/lib/compass/configuration/data.rb:179:in `require'
  /Users/amirm/_sites/compliance.gov/sites/all/themes/officecompliance/config.rb:26:in `get_binding'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `eval'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `parse_string'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `open'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `_parse'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:207:in `with_defaults'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:19:in `configuration_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:69:in `add_project_configuration'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:25:in `configure!'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:15:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/commands/update_project.rb:41:in `initialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /usr/local/bin/compass:22:in `load'
  /usr/local/bin/compass:22:in `<main>'
