### ISSUE TITLE
Compass watch generates incorrect "No such file or directory" error

### ISSUE THREAD

**Issue by tim-arnold** [Compass/compass#1412]
This problem just started happening the past two days on a project that has been running fine for several months.  I am seeing a random "No such file or directory" compass error that stops watch and forces me to restart it.  The thing is, the file I'm editing is where it's supposed to be and will even compile a few times in a row fine and then error out.  When I restart watch it compiles fine again.  It is not file specific and will happen with any scss file in my project.  Here is a full --trace result of two successful compiles followed by the error:

```
user@vm-website:/var/www/compass$ compass watch --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
>>> Change detected at 09:38:38 to: print.scss
overwrite ../stylesheets/print.css
>>> Change detected at 09:38:42 to: print.scss
overwrite ../stylesheets/print.css
>>> Change detected at 09:38:44 to: print.scss
identical ../stylesheets/print.css
Errno::ENOENT on line ["131"] of /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/tree.rb: No such file or directory - /var/www/sass/print.scss
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/tree.rb:131:in `ftype'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/tree.rb:131:in `from_path'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/tree.rb:68:in `set'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/tree.rb:149:in `set'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:59:in `block in add_glob'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:58:in `each'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:58:in `add_glob'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:54:in `block in snapshot'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:54:in `each'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:54:in `snapshot'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:46:in `recache'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/state/directory.rb:13:in `refresh'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/backends/inotify.rb:12:in `block in add_handler'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:201:in `call'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:201:in `block in watch'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/watcher.rb:41:in `[]'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/watcher.rb:41:in `callback!'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/event.rb:128:in `callback!'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in `block in process'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in `each'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:234:in `process'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/rb-inotify-0.9.0/lib/rb-inotify/notifier.rb:217:in `run'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/backends/inotify.rb:20:in `run'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm/monitor.rb:26:in `run'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/fssm-0.2.10/lib/fssm.rb:70:in `monitor'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:87:in `perform'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/bin/compass:44:in `call'
  /usr/local/rvm/gems/ruby-2.0.0-p247/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/bin/compass:23:in `load'
  /usr/local/rvm/gems/ruby-2.0.0-p247/bin/compass:23:in `<main>'
  /usr/local/rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
  /usr/local/rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
user@vm-website:/var/www/compass$
```

**Comment by aiham** [comment]
This just happened to me immediately after 2 successful compiles. Using compass version 0.12.6
