### ISSUE TITLE
RuntimeError: ERROR: Rails.root is nil!

### ISSUE THREAD

**Issue by marczking** [Compass/compass#1462]
when trying to use 1.0.0.alpha.13 I get an error saying

"RuntimeError: ERROR: Rails.root is nil!"

Just used previous compass, so no biggie, just wondering / not sure why I get this...

**Comment by chriseppstein** [comment]
Can you run it with --trace and add the stack trace to this issue so we can debug it?

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by marczking** [comment]
```
/Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/util.rb:450:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin/rails.rb:11:in 'default_options'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin/configuration.rb:33:in 'options'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:38:in 'initialize'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:63:in 'new'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:63:in 'compiler'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:121:in 'options'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin/rails.rb:24:in '<top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'block in require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in 'load_dependency'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:128:in '<top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'block in require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in 'load_dependency'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/compass-core-1.0.0.alpha.13/lib/compass/core.rb:51:in '<top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'block in require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:214:in 'load_dependency'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.1/lib/active_support/dependencies.rb:229:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/compass-1.0.0.alpha.13/lib/compass.rb:15:in 'block in <top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/compass-1.0.0.alpha.13/lib/compass.rb:14:in 'each'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/compass-1.0.0.alpha.13/lib/compass.rb:14:in '<top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in 'block (2 levels) in require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in 'each'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in 'block in require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in 'each'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353@global/gems/bundler-1.3.5/lib/bundler.rb:132:in 'require'`
        `from /Users/MarczKing/Sites/mysite/mysite/config/application.rb:8:in '<top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.1/lib/rails/commands.rb:74:in 'require'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.1/lib/rails/commands.rb:74:in 'block in <top (required)>'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.1/lib/rails/commands.rb:71:in 'tap'`
        `from /Users/MarczKing/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.1/lib/rails/commands.rb:71:in '<top (required)>'`
        `from script/rails:6:in 'require'`
        `from script/rails:6:in '<main>'`
```

hope this helps...

**Comment by chriseppstein** [comment]
I opened a sass bug to track this: https://github.com/nex3/sass/issues/1033
