### ISSUE TITLE
Can't create sourcemaps when ruby and source aren't on the same partition (1.0.0.alpha.17)

### ISSUE THREAD

**Issue by skov** [Compass/compass#1488]
When trying to compile with the sourcemap = true flag I get an error "different prefix". 

```
ArgumentError on line ["500"] of C: different prefix: "C:/" and "D:/git/project/Sites"
C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.2/lib/sass/source/map.rb:128:in 'block in to_json'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.2/lib/sass/source/map.rb:123:in 'each'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.3.0.rc.2/lib/sass/source/map.rb:123:in 'to_json'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:178:in 'compile'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:144:in 'compile_if_required'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:129:in 'block (2 levels) in run'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:127:in 'each'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:127:in 'block in run'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:153:in 'timed'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:126:in 'run'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/update_project.rb:49:in 'perform'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/base.rb:18:in 'execute'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/project_base.rb:19:in 'execute'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:43:in 'perform!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:15:in 'run!'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:30:in 'block in <top (required)>'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in 'call'
C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in '<top (required)>'
C:/Ruby200/bin/compass:23:in 'load'
C:/Ruby200/bin/compass:23:in '<main>'
```

**Comment by jmcguerreiro** [comment]
I'm having the exact same issue. Although, if I leave sourcemap = true and remove the @import "compass"; declaration from my .scss then the source map is created successfully.

**Comment by jmcguerreiro** [comment]
Did anyone found out a workaround for this?

**Comment by Lisaj** [comment]
Hi,
i have this problem to.

**Comment by Lisaj** [comment]
Hello, 
I solved this problem by moving the project to the same disk as the ruby.

**Comment by tbremer** [comment]
I am having this issue as well, and am not able to move my source code to the same partition as ruby.

**Comment by vladyn** [comment]
I'm experiencing same issue, but my ruby and files are on same drive;

```
ArgumentError on line ["55"] of c: wrong number of arguments (2 for 0)
```
