### ISSUE TITLE
Error when using sass --watch  with compass extension while require compass/import-once in config.rb

### ISSUE THREAD

**Issue by deanfields** [Compass/compass#1492]
I'm getting the following error reported to me when trying to use the following command:

sass --compass --watch sass:css --sourcemap

ArgumentError: wrong number of arguments (4 for 3)

This is being pulled in to the config.rb require 'compass/import-once/activate' - Removing this, allows me to watch the files

Stack trace as follows:

<pre>
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/compass-import-once-1.0.1/lib/compass/import-once/importer.rb:7:in `find_relative': wrong number of arguments (4 for 3) (ArgumentError)
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-globbing-1.1.0/lib/sass/globbing/importer.rb:51:in `find'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/compass-import-once-1.0.1/lib/compass/import-once/importer.rb:14:in `find'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/import_node.rb:54:in `block in import'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/import_node.rb:53:in `each'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/import_node.rb:53:in `import'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/import_node.rb:28:in `imported_file'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/import_node.rb:37:in `css_import?'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:282:in `visit_import'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:36:in `visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:153:in `block in visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/stack.rb:79:in `block in with_base'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/stack.rb:115:in `with_frame'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/stack.rb:79:in `with_base'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:153:in `visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:52:in `map'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:52:in `visit_children'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:162:in `block in visit_children'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:174:in `with_environment'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:161:in `visit_children'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:36:in `block in visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:181:in `visit_root'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/base.rb:36:in `visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:152:in `visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/visitors/perform.rb:8:in `visit'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/root_node.rb:36:in `css_tree'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/engine.rb:364:in `_render_with_sourcemap'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/engine.rb:292:in `render_with_sourcemap'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/compass-import-once-1.0.1/lib/compass/import-once/engine.rb:23:in `block in render_with_sourcemap'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/compass-import-once-1.0.1/lib/compass/import-once/engine.rb:29:in `with_import_scope'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/compass-import-once-1.0.1/lib/compass/import-once/engine.rb:22:in `render_with_sourcemap'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:345:in ‘update_stylesheet'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:191:in `block in update_stylesheets'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:188:in `each'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:188:in `update_stylesheets'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin/compiler.rb:223:in `watch'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/plugin.rb:108:in `method_missing'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/exec.rb:508:in `watch_or_update'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/exec.rb:346:in `process_result'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/exec.rb:43:in `parse'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/lib/sass/exec.rb:22:in `parse!'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/gems/sass-3.3.0.rc.2/bin/sass:9:in `<top (required)>'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/bin/sass:23:in '"load"'
.rvm/gems/ruby-2.0.0-p353@sass-development-pre/bin/sass:23:in 'main'
</pre>

**Comment by deanfields** [comment]
I was requiring sass-globbing in my extension, used in on a directory that had no files within it caused the error. commenting this out seems to of allowed the watcher to work
