### ISSUE TITLE
Compilation through Ruby Compass broken

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1493]
As of Compass 1.0.0.alpha.16, the following code (which previously worked) throws errors. I have tested with .16 and .17, but not yet with Master (will post a follow-up comment with Master)

The [Rakefile](https://github.com/Team-Sass/Singularity/blob/1.x.x-3.3.0/Rakefile) used to run these tests can be found in [Singularity's Tests](https://github.com/team-sass/singularity/tree/1.x.x-3.3.0). Currently at .13 through Bundler, updating to .16 or greater will cause the error.

Reduced offending Ruby code ([full code](https://github.com/Team-Sass/Singularity/blob/1.x.x-3.3.0/tests/.unit_tests.rb))

``` ruby
Compass.compiler.sass_files.each do |sass_file|
  test_file_pwd = Compass.compiler.corresponding_css_file(sass_file)
  Compass.compiler.compile sass_file, test_file_pwd
end
```

Stack trace:

``` bash
TypeError: no implicit conversion of nil into String
    /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:181:in `exist?'
    /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/compiler.rb:181:in `compile'
    .unit_tests.rb:34:in `block (2 levels) in <class:TestCompassOutput>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:17:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:657:in `block in _run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `_run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:21:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:774:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:366:in `block (2 levels) in autorun'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:27:in `run_once'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:365:in `block in autorun'
```

**Comment by JohnAlbin** [comment]
It looks like @chriseppstein fixed this in 2df1df7789597fd959165664749ed91702e86f0e :-)

It is a post-1.0.0-alpha.17 commit. I haven't tested the fix in master, but I did see the bug in the 1.0.0.alpha.17.
