### ISSUE TITLE
Compass won't install on Ubunutu 12.04

### ISSUE THREAD

**Issue by Ilyes512** [Compass/compass#1513]
I have tried on 2 different Ubuntu 12.04 (64bits) vagrant boxes to install and use compass. After starting up the vagrant box without any provisioning I perform the fallowing commands:

``` bash
$ sudo apt-get update
$ sudo apt-get upgrade -y

$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
$ . ~/.bash_profile

# I (successfully) confirm that rvm is installed and that the latest ruby is active

rvm requirements # Just to be sure
gem update --system # Just to be sure
gem install compass
```

The above all goes without any errors. It's until I type in: `$ compass -v` that I get the fallowing error:

``` bash
/home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sass/script/node (LoadError)
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:20:in `block in <top (required)>'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/gems/compass-0.12.2/bin/compass:19:in `<top (required)>'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/bin/compass:23:in `load'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/bin/compass:23:in `<main>'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/vagrant/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

Just some more info:
Output of `echo $GEM_HOME` = `/home/vagrant/.rvm/gems/ruby-2.1.0`

I also tried doing this: `/home/vagrant/.rvm/gems/ruby-2.1.0/wrappers/compass -v` and it produces exactly the same error as above.

I also asked this on [SO](http://stackoverflow.com/questions/21079342/cant-use-compass-after-installing-it)

Cause `sass` is a dependency of `compass` it got installed and that works just fine. When I type in `sass -v` I get `Sass 3.3.0.rc.2 (Maptastic Maple)`.

`rvm list`:

``` bash
*** LOCAL GEMS ***

bigdecimal (1.2.3)
bundler (1.5.0)
bundler-unload (1.0.2)
chunky_png (1.2.9)
compass (0.12.2)
executable-hooks (1.2.6)
ffi (1.9.3)
fssm (0.2.10)
gem-wrappers (1.2.4, 1.2.1)
io-console (0.4.2)
json (1.8.1)
listen (1.1.6)
minitest (4.7.5)
psych (2.0.2)
rake (10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
rdoc (4.1.0)
rubygems-bundler (1.4.2)
rvm (1.11.3.8)
sass (3.3.0.rc.2)
test-unit (2.1.0.0)
```

So does anyone experience the same problem with Ubuntu? And does anyone know how I can solve this? I have to say that I am not a Ruby developer so I am totally noob. Is there a essential step that I am missing?

**Comment by lolmaus** [comment]
Try with Ruby 2.0.

**Comment by scottdavis** [comment]
Compass 0.12 will not work with sass 3.3 either upgrade to the compass alpha or downgrade sass

**Comment by Ilyes512** [comment]
Just tried it again hoping I missed something, but nope still the same.

``` bash
$ rvm install 2.0
$ rvm use 2.0
$ ruby -v # To confirm it's 2.0
$ gem install compass
$ compass -v
```

@scottdavis 
Ah, sweet live reloading ^^ I will try it out and let you know right away.

**Comment by Ilyes512** [comment]
Damm, you rock :+1: That did the trick:

``` bash
gem uninstall sass --version 3.3.0.rc.2
gem install sass --version 3.2.13
compass -v # Working :)
```

Thanks for the really really quick answers :) I was stuck for 2 days on this :/

Just a quick question:
Is there a way to flag the `gem install` command to only install stable versions?

**Comment by scottdavis** [comment]
gem install will only install stable versions unless you pass --pre

**Comment by Ilyes512** [comment]
But what about it's dependencies, cause installing compass without any flags installed `sass (3.3.0.rc.2)`. Unless `Release Candidates` are considered stable?

**Comment by scottdavis** [comment]
i think its because we didn't set an upper end dependency in the gemspec
this problem should go away once 1.0 is released /cc @chriseppstein

**Comment by ptkarthikreddy** [comment]
i try last 2 days getting this Error:

$ vagrant box list

## Error:

/home/karthik/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- log4r (LoadError)
    from /home/karthik/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/bin/vagrant:2:in `<main>'
