### ISSUE TITLE
Error using the compass "create" command: 

### ISSUE THREAD

**Issue by NeverFollow** [Compass/compass#1514]
[Mac OSX 10.9.1]

On Page: http://compass-style.org/install/

I was following the given instructions but I got an error:

gem update —system
sudo gem install compass

---

I would like to set up my [ new ] [ compass ] project named [ my_compass_01 ] with  [ compass's ]  starter stylesheets. 
I prefer the  [ CSS based (SCSS) ] Indent based (Sass)  syntax and would like to  use [ compass's recommended ]  directory structure.

---

Now run the following steps in your terminal:
$ gem install compass
$ compass create my_compass_01

---

---

/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sass/script/node (LoadError)

```
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'

from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'

from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'

from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'

from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:20:in `block in <top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:19:in `<top (required)>'

from /usr/bin/compass:23:in `load'
from /usr/bin/compass:23:in `<main>'
```

---

**Comment by chriseppstein** [comment]
What version of Sass do you have installed?

**Comment by luchaos** [comment]
Similar problem when trying to run `compass watch`.

I'm on OSX Mavericks (10.9.1)

After following the install instructions I see:

```
sudo gem install compass
Successfully installed compass-0.12.2
Parsing documentation for compass-0.12.2
1 gem installed
```

Though running `compass watch` gives me:

```
compass watch
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sass/script/node (LoadError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:20:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/bin/compass:19:in `<top (required)>'
    from /usr/bin/compass:23:in `load'
    from /usr/bin/compass:23:in `<main>'
```

Trying to reinstall Sass I get:

```
sudo gem install sass
Fetching: sass-3.2.13.gem (100%)
Successfully installed sass-3.2.13
Parsing documentation for sass-3.2.13
Installing ri documentation for sass-3.2.13
1 gem installed
```

Interestingly enough:

```
sass --version
Sass 3.3.0.rc.2 (Maptastic Maple)
```

Removing 3.3.0 via `gem uninstall` **resolved this issue**

```
sudo gem uninstall sass

Select gem to uninstall:
 1. sass-3.2.10
 2. sass-3.2.13
 3. sass-3.3.0.rc.2
 4. All versions
```

I still do not understand how 3.3.0 got installed in the first place?

**Comment by Nathaniel401** [comment]
I also had 3.3.0.rc.2 installed, I believe it came with the compass package ironically. After uninstalling that version and installing the current stable build this problem was resolved for me as well!

Thanks for this!

Cheers,
Nathaniel

**Comment by billyxs** [comment]
I too had to delete SASS version 3.3.0.rc.3 from my gems to get it sorted out.  Thanks!

**Comment by aCandidMind** [comment]
Same here with sass-3.3.0.rc.4. Uninstalling it helped me as well.

**Comment by kevinSuttle** [comment]
+1 for uninstalling an RC

**Comment by chriseppstein** [comment]
use compass 1.0 to use sass 3.3+
