### ISSUE TITLE
errors and problems after updating compass

### ISSUE THREAD

**Issue by PDMackinnon** [Compass/compass#1516]
after updates, I had problems, so I did uninstall and reinstall, as well as updates to gem and sass. now its really broken as follows:

```
compass --version
/Library/Ruby/Gems/1.8/gems/haml-3.0.25/lib/sass/script/literal.rb:7: superclass mismatch for class Literal (TypeError)
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:5
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:20
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:19
    from /usr/bin/compass:23:in `load'
    from /usr/bin/compass:23

```

Well, I don't know what it means, but I would like a method to clean things up; perhaps update, re-install, whatever to get this to work.. regretting having tried to update at all. Here is my approach which may give clues to what went wrong:

```
compass --version
Compass 0.11.beta.5


gem list

*** LOCAL GEMS ***

chunky_png (1.1.0)
compass (0.11.beta.5, 0.10.6)
ffi (1.0.6)
haml (3.0.25)
rake (0.8.7)
rvm (1.2.6)
sass (3.1.0.alpha.252)
tidy_ffi (0.1.3)

sudo gem update compass

Successfully installed chunky_png-1.2.9
Successfully installed fssm-0.2.10
Successfully installed compass-0.12.2
Gems updated: chunky_png, fssm, compass


leads to 

/Library/Ruby/Site/1.8/rubygems/dependency.rb:298:in `to_specs': Could not find 'sass' (~> 3.1) - did find: [sass-3.1.0.alpha.252] (Gem::LoadError)


.. then further research leads to

sudo gem update --system
sudo gem update sass


hence
gem list

*** LOCAL GEMS ***

chunky_png (1.2.9, 1.1.0)
compass (0.12.2, 0.11.beta.5, 0.10.6)
ffi (1.0.6)
fssm (0.2.10)
haml (3.0.25)
listen (1.1.6)
rake (0.8.7)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
rubygems-update (2.2.1)
rvm (1.2.6)
sass (3.3.0.rc.2, 3.1.0.alpha.252)
tidy_ffi (0.1.3)


but ..

/Library/Ruby/Gems/1.8/gems/haml-3.0.25/lib/sass/script/literal.rb:7: superclass mismatch for class Literal (TypeError)
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:5
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/lib/compass.rb:4
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:20
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/1.8/gems/compass-0.12.2/bin/compass:19
    from /usr/bin/compass:19:in `load'
    from /usr/bin/compass:19


sudo gem uninstall compass

Successfully uninstalled compass-0.10.6
Successfully uninstalled compass-0.11.beta.5
Remove executables:
    compass

in addition to the gem? [Yn]  y
Removing compass
Successfully uninstalled compass-0.12.2

sudo gem install compass

```

which gets me to the current position.

Any help or ideas as what the problem can be and how to fix it ?

**Comment by mprins** [comment]
you might try to remove any and all sass and compass and then only install compass 0.12.2 which should pull in the right version of sass (whcih I think shoould be 3.2.13)

Or maybe look into using bundler...

**Comment by PDMackinnon** [comment]
OK. I may have solved it as far as I require for now. I don't work with ruby much, but I found a way as I had rvm installed and it has another ruby which I switched to 

```
rvm use ruby-1.9.2-p180
```

Then I found using

```
gem list
```

that I have fewer gem installs in there, and just started over for compass install. That seems to work now.

**Comment by ScottBarkman** [comment]
Had this issue as well. Solved after removing sass & compass, and reinstalling both.

**Comment by chriseppstein** [comment]
Good call. Please upgrade to 1.0 now.

**Comment by mkrishtopa** [comment]
have this issue too
