### ISSUE TITLE
Running `compass` outside of Bundler control throws errors

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#1538]
Issue with Compass 1.0.0.alpha.17

If I'm under Bundler control, this doesn't happen, but if I try and run any Compass command from outside Bundler control (including `compass -v`), I get the following error:

``` bash
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1990:in `raise_if_conflicts': Unable to activate compass-rails-1.0.3, because compass-1.0.0.alpha.17 conflicts with compass (< 0.14, >= 0.12.2) (Gem::LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1163:in `activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:181:in `rescue in try_activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:178:in `try_activate'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:109:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/frameworks.rb:138:in `block in discover_gem_extensions!'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/frameworks.rb:137:in `each'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/frameworks.rb:137:in `discover_gem_extensions!'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/frameworks.rb:152:in `discover_extensions!'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/commands.rb:14:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /usr/local/gems/compass-1.0.0.alpha.17/lib/compass/exec.rb:7:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:58:in `require'
    from /usr/local/gems/compass-1.0.0.alpha.17/bin/compass:21:in `block in <top (required)>'
    from /usr/local/gems/compass-1.0.0.alpha.17/bin/compass:8:in `fallback_load_path'
    from /usr/local/gems/compass-1.0.0.alpha.17/bin/compass:19:in `<top (required)>'
    from /usr/bin/compass:23:in `load'
    from /usr/bin/compass:23:in `<main>'
```

**Comment by scottdavis** [comment]
Your are having a gem conflict with compass rails

**Comment by chriseppstein** [comment]
This is a problem. We discover gem extensions now. I think we should fail silently if it doesn't load.
