### ISSUE TITLE
Why are there -ms- and -o- prefixes for everything?

### ISSUE THREAD

**Issue by thany** [Compass/compass#1546]
Compass generates -ms- for all CSS3 properties that also need prefixes -moz- and -webkit-. This is not neccesary. There is no version of MSIE that needs -ms- prefixes for _most_ properties. The same is true for the -o- prefix and Opera. Opera doesn't need prefixes for almost all properties.

From the top of my head, the only properties that need the -ms- prefix are (apart from MS extensions), transform and gradients.

Can unneccesary -ms- & -o- prefixes please be removed from rendered css?

Using Compass 0.12.2, Sass 3.2.14, Ruby 2.0.0p353, Windows 7 x64

**Comment by Anahkiasen** [comment]
Try the alpha 0.13 of Compass which completely changes the way prefixes are generated to use Can I Use usage data. It even has a debug feature that explains which each prefix was added.

**Comment by thany** [comment]
Ooh, that sounds good. Two questions:
1) How do I update Compass to 0.13?
2) When will it be released? :P

**Comment by Anahkiasen** [comment]
You can do `gem install compass --pre` to get it. No idea when it'll be released though, I'm not working on it, just passing the message. :)

**Comment by thany** [comment]
Hm, that wasn't such a good idea, as it turns out:

```
compass watch --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
LoadError on line ["126"] of C: cannot load such file -- wdm
  C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:199:in `load_dependent_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapters/windows.rb:33:in `load_dependent_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:190:in `usable?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapters/windows.rb:25:in `usable?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `usable_and_works?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:49:in `block in select_and_initialize'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `each'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `select_and_initialize'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:272:in `initialize_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:264:in `setup'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:64:in `start!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/watcher/project_watcher.rb:31:in `watch!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/watch_project.rb:48:in `perform'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/project_base.rb:19:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:30:in `block in <top (required)>'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `call'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `<top (required)>'
  C:/Ruby200-x64/bin/compass:23:in `load'
  C:/Ruby200-x64/bin/compass:23:in `<main>'
```

Also did a `gem update --system` and `gem update` after this, to no avail.
So unfortunately, I can't verify if the alpha version solves this issue...

/edit
Okay, I think my installation is crapped now.. I uninstalled all versions of compass, reinstalled the latest (for which it fetched 0.12.2) and compass (no matter what arguments!) now returns this:

```
C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- sass/script/node (LoadError)
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:20:in `block in <top (required)>'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:19:in `<top (required)>'
        from C:/Ruby200-x64/bin/compass:23:in `load'
        from C:/Ruby200-x64/bin/compass:23:in `<main>'
```

Wow, so now what?

**Comment by thany** [comment]
Okay, uninstalled all gems, reinstalled sass & compass, and it's working again.
Why the hell that solves the erros, I don't know. It feels like just reinstalling the problem, but even in the world of ruby, it appears reinstalling may help...

A warning to other users then: **Don't install compass 0.13 yet**

Oh and the original issue remains ;)

**Comment by Anahkiasen** [comment]
I think it's an issue with your installation, I've been using 0.13 for a while and never had that problem.

**Comment by thany** [comment]
It sure is an issue, but I'm not adept enough to see what was wrong. I'm sure the Compass developers can figure it out before 0.13 goes final. I'd be happy to supply any additional information, just ask.

Well, if this error is to be solved, I might as well try again and supply some version information. Here's what `gem install compass -pre` caused ruby to install:

```
Fetching: rb-fsevent-0.9.4.gem (100%)
Successfully installed rb-fsevent-0.9.4
Fetching: ffi-1.9.3-x64-mingw32.gem (100%)
Successfully installed ffi-1.9.3-x64-mingw32
Fetching: rb-inotify-0.9.3.gem (100%)
Successfully installed rb-inotify-0.9.3
Fetching: rb-kqueue-0.2.0.gem (100%)
Successfully installed rb-kqueue-0.2.0
Fetching: listen-1.1.6.gem (100%)
Successfully installed listen-1.1.6
Fetching: sass-3.3.0.rc.2.gem (100%)
Successfully installed sass-3.3.0.rc.2
Fetching: multi_json-1.8.4.gem (100%)
Successfully installed multi_json-1.8.4
Fetching: compass-core-1.0.0.alpha.16.gem (100%)
Successfully installed compass-core-1.0.0.alpha.16
Fetching: compass-import-once-1.0.2.gem (100%)
Successfully installed compass-import-once-1.0.2
Fetching: compass-1.0.0.alpha.17.gem (100%)
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
Successfully installed compass-1.0.0.alpha.17
Parsing documentation for compass-1.0.0.alpha.17
Installing ri documentation for compass-1.0.0.alpha.17
Parsing documentation for compass-core-1.0.0.alpha.16
Installing ri documentation for compass-core-1.0.0.alpha.16
Parsing documentation for compass-import-once-1.0.2
Installing ri documentation for compass-import-once-1.0.2
Parsing documentation for ffi-1.9.3-x64-mingw32
Installing ri documentation for ffi-1.9.3-x64-mingw32
Parsing documentation for listen-1.1.6
Installing ri documentation for listen-1.1.6
Parsing documentation for multi_json-1.8.4
Installing ri documentation for multi_json-1.8.4
Parsing documentation for rb-fsevent-0.9.4
Installing ri documentation for rb-fsevent-0.9.4
Parsing documentation for rb-inotify-0.9.3
Installing ri documentation for rb-inotify-0.9.3
Parsing documentation for rb-kqueue-0.2.0
Installing ri documentation for rb-kqueue-0.2.0
Parsing documentation for sass-3.3.0.rc.2
Installing ri documentation for sass-3.3.0.rc.2
10 gems installed
```

One or more of these might be incompatible. Or a bug in the prerelease of compass.

**Comment by chriseppstein** [comment]
Hi @thany, it seems like the watcher is not working for you on your windows system. I don't have windows for testing, but if someone can debug this, I'd be happy to accept a patch for it. In the meantime, try adding `--poll` to the watch command.

**Comment by thany** [comment]
Already figured it out, as stated in #1548. The wdm module is a requirement (for windows only, apparently..) but didn't come along in the dependencies.

Btw, settings up a Windows VM is easy, Microsoft has free downloads for a handful of configs ;)

**Comment by blaja** [comment]
Hi guys, I use the latest version of Sass and Compass.I need to turn off support for legacy browsers but it seems that it's not working.For example I used (@)include background-size(? ?); and it generates  -o-  -moz- but I need  only -webkit-. Is it possible to turn that off with variables before compass import like in earlier versions? With latest version it seems that it's not working.

**Comment by chriseppstein** [comment]
Documentation on how to turn vendor prefixes in 1.0: http://beta.compass-style.org/help/documentation/tuning-vendor-prefixes/
