### ISSUE TITLE
1.0.0.alpha.17: compass watch not working

### ISSUE THREAD

**Issue by thany** [Compass/compass#1548]
Just freshly installed the latest prerlease of compass, and executed `compass watch` on my project. Worked absolutely fine in 0.12.2. In 1.0.0.alpha.17, I get this:

```
>>> Compass is watching for changes. Press Ctrl-C to Stop.
LoadError on line ["55"] of C: cannot load such file -- wdm
  C:/Ruby200-x64/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:199:in `load_dependent_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapters/windows.rb:33:in `load_dependent_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:190:in `usable?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapters/windows.rb:25:in `usable?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:182:in `usable_and_works?'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:49:in `block in select_and_initialize'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `each'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/adapter.rb:47:in `select_and_initialize'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:272:in `initialize_adapter'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:264:in `setup'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/listen-1.1.6/lib/listen/listener.rb:64:in `start!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/watcher/project_watcher.rb:31:in `watch!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/watch_project.rb:48:in `perform'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/commands/project_base.rb:19:in `execute'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:30:in `block in <top (required)>'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `call'
  C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.17/bin/compass:44:in `<top (required)>'
  C:/Ruby200-x64/bin/compass:23:in `load'
  C:/Ruby200-x64/bin/compass:23:in `<main>'
```

I'm not sure how to deal with this. Is there a thing called "wdm" that's missing or something? And if so, where/how do I get it?

Output of uninstalling stable, and installing prerelease:

```
C:\Windows\system32>gem uninstall compass
Remove executables:
        compass

in addition to the gem? [Yn]  y
Removing compass
Successfully uninstalled compass-0.12.2

C:\Windows\system32>gem install compass --pre
Fetching: sass-3.3.0.rc.2.gem (100%)
Successfully installed sass-3.3.0.rc.2
Fetching: compass-1.0.0.alpha.17.gem (100%)
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
Successfully installed compass-1.0.0.alpha.17
Parsing documentation for compass-1.0.0.alpha.17
Installing ri documentation for compass-1.0.0.alpha.17
Parsing documentation for sass-3.3.0.rc.2
Installing ri documentation for sass-3.3.0.rc.2
2 gems installed
```

Specs:
Compass version: 1.0.0.alpha.17
Sass version: 3.3.0.rc.2
Gem version: 2.2.2
Ruby version: 2.0.0p353
Windows 7 x64

**Comment by thany** [comment]
`gem install wdm`
And it works. Can this please be added to the depencies, so it'll install automatically just like sass does?

**Comment by chriseppstein** [comment]
we can't make it a dependency because it shouldn't be installed into everyone's system, but we can certainly make a better error message.

**Comment by Arcovion** [comment]
Listen 2.x.x has better error messages now with Alpha 20, this can be closed I think.
