### ISSUE TITLE
Compass alpha.18 + Sass 3.3.0.rc4 breaks on Windows

### ISSUE THREAD

**Issue by jonjaques** [Compass/compass#1571]
```
Warning:
   ! NoMethodError on line ["87"] of C: undefined method `index' for nil:NilClass
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/actions.rb:83:in `basename'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:212:in `handle_exception'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:132:in `rescue in block (2 levels) in run'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:128:in `block (2 levels) in run'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:127:in `each'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:127:in `block in run'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:153:in `timed'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/compiler.rb:126:in `run'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/commands/update_project.rb:49:in `perform'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/commands/base.rb:18:in `execute'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/commands/project_base.rb:19:in `execute'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/lib/compass/exec/sub_command_ui.rb:15:in `run!'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/bin/compass:30:in `block in <top (required)>'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/bin/compass:44:in `call'
   !   C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/compass-1.0.0.alpha.18/bin/compass:44:in `<top (required)>'
   !   C:/Ruby200-x64/bin/compass:23:in `load'
   !   C:/Ruby200-x64/bin/compass:23:in `<main>'
```

Here are my local gems:

```
*** LOCAL GEMS ***

bigdecimal (1.2.0)
celluloid (0.15.2)
chunky_png (1.3.0)
compass (1.0.0.alpha.18, 1.0.0.alpha.16)
compass-core (1.0.0.alpha.17)
compass-import-once (1.0.2)
ffi (1.9.3 x64-mingw32)
io-console (0.4.2)
json (1.7.7)
listen (2.4.1, 1.1.6)
minitest (4.3.2)
multi_json (1.8.4)
psych (2.0.0)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.2)
rdoc (4.0.0)
rubygems-update (2.2.2)
sass (3.3.0.rc.4)
test-unit (2.0.0.0)
timers (1.1.0)
```

I was able to revert Compass and Sass back to `alpha.17` and `3.3.0.rc.2`, respectively, which runs okay.

Not sure where the problem lies (Sass vs. Compass), but happy to give more info if anybody needs.

**Comment by neilhem** [comment]
`sourcemap = true` in your compass configuration?

**Comment by mprins** [comment]
seems a dup of #1557

**Comment by jonjaques** [comment]
Yup, it's a dupe - sorry I didn't see that one before.
