### ISSUE TITLE
compass-import-once causes `compass compile` to fail on Windows since 1.0.4

### ISSUE THREAD

**Issue by andypearson** [Compass/compass#1642]
We've just had a lot of fun trying to debug this over the past few hours...

The crux of the issues is:

On OS X the generated output cache path for an import-once scss file looks like:
`75fcaf1b4852ceb732871195e41567cc2a7d8997//Library/Ruby/Gems/2.0.0/gems/compass-0.12.3/frameworks/compass/stylesheets/compass/layout/_grid-background.scssc`

On Windows it'll look like:
`75fcaf1b4852ceb732871195e41567cc2a7d8997/C:/RUBY193/lib/
ruby/gems/1.9.1/gems/compass-0.12.2/frameworks/compass/stylesheets/compass`

When it comes to creating the cache file that `C:` is the problem - it'll cause Windows to bail out with an Errno::ENOENT error, whilst Unix is happy to go ahead and create the file despite the fact it'll be several directories deep.

The problem seems to come for the following method, in 1.0.3 it looked like:

```
def key(uri, options, *args)
  if uri =~ /^\(NOT IMPORTED\)/
    ["(import-once)", "dummy_engine"]
  else
    super
  end
end
```

And in 1.0.4 it looks like:

```
def key(uri, options, *args)
  if uri =~ /^\(NOT IMPORTED\) (.*)$/
    ["(import-once)", $1]
  else
    super
  end
end
```

It looks like a relatively simple fix; massage `$1` a little bit to remove the project path before giving it back to sass. Thoughts?

Here is a screenshot showing roughly what is going on, grabbed hastily from @deeja's machine.

![screeenshot-edit](https://cloud.githubusercontent.com/assets/857/2671111/7d4f19d4-c0d6-11e3-8160-d846773afacd.jpg)

**Comment by clauzf** [comment]
thanks you for this post, after read your post, I fixed it by replace the "key" function with the old version one.

**Comment by derekwheee** [comment]
This looks like the same issue I'm having in #1640

**Comment by andypearson** [comment]
@frxnz Yup, that does indeed look like the same issue.

**Comment by deeja** [comment]
Might mention that the file affected on my machine is:
**C:\Ruby193\lib\ruby\gems\1.9.1\gems\compass-import-once-1.0.3\lib\compass\import-once\importer.rb**

**Comment by nickjules** [comment]
I have exactly the same problem, but I am a designer and am really struggling 
with the techy side, here is the error and the gems I have in a gem file, please could someone advise ( as if speaking to a child might help with my skill level!) Many thanks

![error1](https://cloud.githubusercontent.com/assets/7632785/3016813/5b928a96-df72-11e3-85b0-e5c83d00a3c7.jpg)

![error_gems](https://cloud.githubusercontent.com/assets/7632785/3016815/5ef0cba8-df72-11e3-81a6-a840c8f7839a.jpg)

**Comment by nickjules** [comment]
sorry to have posted the above, all I needed was @import "compass/css3"; and then it compiled without error. I am so new to all this.......

**Comment by ymcheung** [comment]
I've got the same problem but dunno how to solve it.
Do the same as @deeja 's screenshot?

**Comment by deeja** [comment]
If you don't mind what version you use, you can roll back a bit to where it works: 

```
call gem uninstall compass-import-once -a
call gem uninstall compass -a
call gem uninstall sass -a

call gem install sass -v 3.2.14 
call gem install compass -v 0.12.3 
call gem install compass-import-once -v 1.0.3
```

**Comment by ymcheung** [comment]
My colleagues use susy2 so that I have to install at least sass v3.3 and compass 1.0.
Can I just install compass-import-once 1.0.3 ?

**Comment by chriseppstein** [comment]
I've rewritten the compass compiler to use Sass's internal compiler and there's been an import once update since then. Can you verify this is fixed in 1.0?

**Comment by AirQuick** [comment]
It depends on the path length. Steps to repro:
1.  Install Ruby, Sass and Compass in "p:\Ruby\test1".
2.  Create an empty directory: "p:\proj"
3.  In "p:\proj", run "compass create".
4.  Insert a '@import "compass";' line into "p:\proj\sass\screen.scss".
5.  Run "compass compile --force" in "p:\proj". => Success
6.  Rename the Ruby installation directory to a longer one: "p:\Ruby\test123456789012345678901234567890"
7.  Run "compass compile --force" in "p:\proj". => Fail

> error sass/screen.scss (P:/Ruby/test123456789012345678901234567890/lib/ruby/
> 2.0.0/tempfile.rb:146:in `initialize': No such file or directory - p:/proj/.sass
> -cache/75fcaf1b4852ceb732871195e41567cc2a7d8997/P%058%092Ruby%092test12345678901
> 2345678901234567890%092lib%092ruby%092gems%0922.0.0%092gems%092compass-core-1.0.
> 0%092stylesheets%092compass%092utilities%092general%092_hacks.scssc20140819-1077
> 2-1viz04c)
> Compilation failed in 1 files.

Ruby 2.0.0 451 x64
Sass 3.4.0 (Selective Steve)
Compass 1.0.0 (Polaris)

Seems like the current naming convention goes easily beyond MAX_PATH?

**Comment by JustJenFelice** [comment]
I think I've got much of the same here:

```
Errno::ENOENT on line ["50"] of /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb: No such file or directory @ realpath_rec - /sass
```

Compass 1.0.1 (Polaris)
Sass 3.4.0 (Selective Steve)
Ruby-2.1.1
on Mac OSX 10.9.4

Here's the full backtrace:

```
Errno::ENOENT on line ["50"] of /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb: No such file or directory @ realpath_rec - /sass
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb:50:in `realpath'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb:50:in `block in initialize'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb:50:in `map'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen/listener.rb:50:in `initialize'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen.rb:70:in `new'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen.rb:70:in `_add_listener'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/listen-2.7.9/lib/listen.rb:27:in `to'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:389:in `block in create_listener'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:388:in `map'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:388:in `create_listener'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:323:in `watch'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/sass_compiler.rb:46:in `watch!'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/commands/watch_project.rb:41:in `perform'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/bin/compass:44:in `call'
  /Users/username/.rvm/gems/ruby-2.1.1@project/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /Users/username/.rvm/gems/ruby-2.1.1@project/bin/compass:23:in `load'
  /Users/username/.rvm/gems/ruby-2.1.1@project/bin/compass:23:in `<main>'
  /Users/username/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `eval'
  /Users/username/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

I've been wrangling with this ever since I updated Compass and am now resorting to rolling-back. If anybody has any other suggestions for a possible fix, I'd love to hear it.

**Comment by ancientrs** [comment]
I solved this issue with @andypearson 's way, that I replace the "key" function with the old version(1.0.3)  on Windows.  Thanks a lot.

**Comment by JustJenFelice** [comment]
@ancientrs - thanks! I just rolled back and managed to get things working again. There does seem to be some significant differences in how the versions compile (as previously mentioned)...maybe it has to do with the handling of project_path. No sure yet. Regardless, I'm up and running again for now. Many thanks :+1:

**Comment by bidah** [comment]
It worked for me after @deeja 's way. Thanks

**Comment by Shupal** [comment]
thanks @deeja 
now it works!

**Comment by kkbruce** [comment]
@Shupal 
My OS is Windows 8.1, @deeja steps is works for me.

**Comment by pdrosos** [comment]
Same issue here on Windows 7. It seems that we also have the problem with the long paths. 
For now we downgraded as proposed above and the problem is gone, but we would like to use the latest version. When and in which of the next versions could we expect a fix of this issue?

Thanks.

**Comment by ghost** [comment]
@andypearson, thank you! You helped me greatly!

**Comment by Frikki** [comment]
Thank you, @deeja and @andypearson

**Comment by sambody** [comment]
I solved it using a solution suggested in issue #1791.
Just setting 
cache = true
cache_path = 'C:/temp/sass/'
I didn't have to uninstall anything.

**Comment by jhoaquinsito** [comment]
Thanks @sambody . I've set cache and cache_path and everything works fine without downgrade.

**Comment by ngadiono** [comment]
Thanks @sambody you safe my life haha, it worked!!!
