### ISSUE TITLE
Sprite generation fails with no parent due to image filename wrong casing

### ISSUE THREAD

**Issue by gmarziou** [Compass/compass#1740]
Sprite creation fails due to some mismatch in image filename. My environment is the following:
- ubuntu 14.04
- ruby 1.9.3
- sass 3.3.14
- compass 0.12.7

I have set up a git repository that exhibits the problem: https://github.com/gmarziou/compass_test_case.git

I’m creating sprites from flags directory which contains a hundred of country flags as PNG images using 3 letters country codes all upper cased. This works well until it reaches TAN.png where it fails saying that the sprite has no parent, I looked at the name of the sprite it is 'tan' while it should be 'TAN'.

```
$ compass compile --trace
unchanged sass/print.scss
unchanged images/flags-s3364e72450.png
NoMethodError on line ["100"] of /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/sass_extensions/functions/sprites.rb: undefined method `parent' for nil:NilClass
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/script/funcall.rb:112:in `_perform'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:204:in `visit_if'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:161:in `block (3 levels) in visit_each'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:161:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:161:in `block (2 levels) in visit_each'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:159:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:159:in `block in visit_each'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:158:in `visit_each'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:139:in `block (2 levels) in compile'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:138:in `block in compile'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/logger.rb:45:in `red'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:137:in `compile'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:118:in `compile_if_required'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:103:in `block (2 levels) in run'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `each'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:101:in `block in run'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:126:in `timed'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/compiler.rb:100:in `run'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/commands/update_project.rb:45:in `perform'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/commands/base.rb:18:in `execute'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/commands/project_base.rb:19:in `execute'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/bin/compass:30:in `block in <top (required)>'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/bin/compass:44:in `call'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/gems/compass-0.12.7/bin/compass:44:in `<top (required)>'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `load'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/bin/compass:19:in `<main>'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `eval'
  /home/gael/.rvm/gems/ruby-1.9.3-p327/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by gmarziou** [comment]
I renamed all my images to lower cases with this script:

```
for i in *; do mv $i `echo $i | tr [:upper:] [:lower:]`; done
```

This fixed the problem so there is something related to file naming.

**Comment by scottdavis** [comment]
`compass 0.12.7` im curious if you have tried this against the latest pre release? alot has changed between 0.12 and now this may be a non issue once 1.0 is live.

**Comment by gmarziou** [comment]
I just tried Compass 1.0.0.rc.0 on ruby 2.1.2 and got the error below which could be the same.
Then I renamed all images to lower case and again it passed.

```
ael@ubuntu:~/compass_test_case$ compass compile --trace
NoMethodError on line ["111"] of /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb: undefined method `sass_filename' for #<NoMethodError: undefined method `parent' for nil:NilClass>
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb:31:in `block (2 levels) in initialize'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/callbacks.rb:61:in `[]'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/callbacks.rb:61:in `block in run_compilation_error'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/callbacks.rb:61:in `each'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/callbacks.rb:61:in `run_compilation_error'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/plugin/compiler.rb:490:in `rescue in update_stylesheet'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/plugin/compiler.rb:475:in `update_stylesheet'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/plugin/compiler.rb:214:in `block in update_stylesheets'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/plugin/compiler.rb:208:in `each'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/sass-3.4.0.rc.3/lib/sass/plugin/compiler.rb:208:in `update_stylesheets'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/sass_compiler.rb:36:in `compile!'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/commands/update_project.rb:49:in `perform'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/commands/base.rb:18:in `execute'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/commands/project_base.rb:19:in `execute'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/bin/compass:30:in `block in <top (required)>'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/bin/compass:44:in `call'
  /home/gael/.rvm/gems/ruby-2.1.2/gems/compass-1.0.0.rc.0/bin/compass:44:in `<top (required)>'
  /home/gael/.rvm/gems/ruby-2.1.2/bin/compass:23:in `load'
  /home/gael/.rvm/gems/ruby-2.1.2/bin/compass:23:in `<main>'
  /home/gael/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
  /home/gael/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chriseppstein** [comment]
easy, low-risk to fix.

**Comment by gmarziou** [comment]
Thanks
