### ISSUE TITLE
Compass Configuration relies on SpriteImporter from outside core

### ISSUE THREAD

**Issue by tdreyno** [Compass/compass#1741]
When running `::Compass.configuration.to_sass_engine_options` with RC1:

```
  undefined method `new' for nil:NilClass
  /Users/thomasreynolds/.rvm/gems/ruby-2.1.1/gems/compass-core-1.0.0.rc.1/lib/compass/configuration/adapters.rb:89:in `sass_load_paths'
  /Users/thomasreynolds/.rvm/gems/ruby-2.1.1/gems/compass-core-1.0.0.rc.1/lib/compass/configuration/adapters.rb:59:in `to_sass_engine_options'
  /Users/thomasreynolds/Sites/middleman-compass/lib/middleman-compass/extension.rb:53:in `sass_options'
```

This is from the line in `adapters.rb` that looks like this:

```
        load_paths << Compass::SpriteImporter.new
```

Which makes sense, if Spriting isn't in core.

**Comment by chriseppstein** [comment]
sigh, this is what happens when you don't move the test associated with the feature.

**Comment by chriseppstein** [comment]
fixed.

**Comment by tdreyno** [comment]
Thanks Chris, we'll be in a beta for a long long while. I'll check in when the sprite gem is split out.
