### ISSUE TITLE
Windows Compass errors.  Any suggestions?

### ISSUE THREAD

**Issue by rhinowrk** [Compass/compass#1763]
I'm going to list two issues, only because i think they are related.  If this assumption is in error I will repost as separate issues.

Issue #1:
C:\xampp\htdocs\project>compass watch

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > ArgumentError on line ["500"] of C: different prefix: "/" and "C:\xampp/htdocs/project/css/sass"
> > > Run with --trace to see the full backtrace
> > > - Note: config.rb seems to be set up properly.  Any change to config.rb will allow Compass to proceed normally again, including adding a simple space anywhere in the file and saving it.

issue #2:
C:\xampp\htdocs\project>compass watch
 modified config.rb
    clean css
   delete css/style.css
   delete css/under-ie9.css

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > >     write css/style.css
> > >     write css/under-ie9.css
> > >  modified css/sass/partials/_project.scss
- Note: Compass just hangs here indefinitely.  Upon ctrl+c the following is outputted:

C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:72:in `sleep': Interrupt
        from C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:72:in`block (2 levels) in
wait'
        from C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:68:in `handle_interrupt'
        from C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:68:in`block in wait'
        from C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:66:in `handle_interrupt'
        from C:/Ruby200-x64/lib/ruby/2.0.0/thread.rb:66:in`wait'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/thread_handle.rb:37:in `block in join'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/thread_handle.rb:37:in`synchronize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/thread_handle.rb:37:in `join'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/actor.rb:96:in`join'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/actor_system.rb:79:in `block (2 levels) in shutdown'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/actor_system.rb:77:in`each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/actor_system.rb:77:in `block in shutdown'
        from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:66:in`timeout'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid/actor_system.rb:66:in `shutdown'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid.rb:156:in`shutdown'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0.pre3/lib/c
elluloid.rb:145:in `block in register_shutdown'
Terminate batch job (Y/N)?

Any info greatly appreciated.  Thanks!

**Comment by chriseppstein** [comment]
is the wdm gem installed?

**Comment by rhinowrk** [comment]
sorry for the response delay.  yes sir it is.

**Comment by chriseppstein** [comment]
If you pass the `--poll` option does it work for you?

**Comment by rhinowrk** [comment]
I'm sorry, Chris, unfamiliar with the --poll option.

**Comment by chriseppstein** [comment]
@rhinowrk `compass watch --poll`

**Comment by rhinowrk** [comment]
C:\xampp\htdocs\project>compass watch --poll

> > > Compass is watching for changes. Press Ctrl-C to Stop.
> > > ArgumentError on line ["500"] of C: different prefix: "/" and "C:\xampp/htdocs/project/css/sass"
> > > Run with --trace to see the full backtrace

**Comment by mikapa** [comment]
I have the same problem ...

/c/wamp/www/blog/sites/all/themes/mika
$compass watch --poll

Compass is watching for changes. Press Ctrl-C to Stop.
ArgumentError on line ["465"] of c: different prefix: "c:/" and "c:\wamp/www/blog/sites/all/themes/mika/sass"
Run with --trace to see the full backtrace

**Comment by chriseppstein** [comment]
Ugh. windows makes me :cry:

**Comment by Shupal** [comment]
have you install ruby and compass via rubyinstaller?

**Comment by LennyBalston** [comment]
I had exactly the same error as mikapa.

I resolved this issue by changing the gemfile `gem 'sass-globbing', '1.1.0'`
and running `bundle install` again.
