### ISSUE TITLE
Cannot use sprites - Windows 8

### ISSUE THREAD

**Issue by ivanovjaroslaw** [Compass/compass#1788]
When I try to use sprites:

@import "compass/utilities/sprites";
@import "sprites/*.png";

I get the next error:

C:\WebServers\home\work.ru\www>compass compile --trace
Errno::ENOENT on line ["346"] of C: No such file or directory - C:/WebServers/home/work.ru/www/.sass-cache/75
fcaf1b4852ceb732871195e41567cc2a7d8997/C%058%092Ruby193%092lib%092ruby%092gems%0921.9.1%092gems%092compass-co
re-1.0.1%092stylesheets%092compass%092utilities%092general%092_hacks.scssc20140823-10196-bwdx1y.lock
  C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:346:in `rmdir'
  C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:338:in`ensure in locking'
  C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:338:in `locking'
  C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:144:in`block in initialize'
  C:/Ruby193/lib/ruby/1.9.1/tmpdir.rb:133:in `create'
  C:/Ruby193/lib/ruby/1.9.1/tempfile.rb:134:in`initialize'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/util.rb:1193:in `new'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/util.rb:1193:in`atomic_create_and_write_file'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/cache_stores/filesystem.rb:39:in `_store'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/cache_stores/base.rb:51:in`store'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/cache_stores/chain.rb:19:in `block in store'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/cache_stores/chain.rb:19:in`each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/cache_stores/chain.rb:19:in `store'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/engine.rb:404:in`_to_tree'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/engine.rb:299:in `to_tree'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:178:in`block in comput
e_dependencies'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/tree/node.rb:193:in `block (2 levels) in each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/tree/node.rb:192:in`each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/tree/node.rb:193:in `block in each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/tree/node.rb:193:in`each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/tree/node.rb:193:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:174:in`grep'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:174:in `compute_depende
ncies'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:149:in`dependencies'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_st
ale?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:166:in`block in depend
ency_updated?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in`any?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_st
ale?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:166:in`block in depend
ency_updated?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in`any?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_st
ale?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:166:in`block in depend
ency_updated?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in`any?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_st
ale?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:166:in`block in depend
ency_updated?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:81:in `call'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:81:in`stylesheet_modif
ied_since?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs
_update?'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:210:in`block in update_styleshe
ets'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:208:in `each'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:208:in`update_stylesheets'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/sass_compiler.rb:40:in `compile!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/update_project.rb:49:in`perform'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in`execute'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in`run!'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in`call'
  C:/Ruby193/lib/ruby/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  C:/Ruby193/bin/compass:23:in`load'
  C:/Ruby193/bin/compass:23:in `<main>'

**Comment by ivanovjaroslaw** [comment]
So, I find some kind solution. Don't use import with sprites (*.png). Use sprite-map.
Thanks to @dreamersp in issue https://github.com/Compass/compass/issues/1657
