### ISSUE TITLE
Compile command hangs with ruby 2.1.0-p0

### ISSUE THREAD

**Issue by bcardarella** [Compass/compass#1810]
I haven't confirmed with other versions but I have a simple script:

``` ruby
css_dir = "app/styles"
sass_dir = "app/sass"
output_style = :compressed
```

I run `compass compile -c compass.rb` and it just hangs. The ruby process eats 99% of my CPU.

**Comment by bcardarella** [comment]
Any other info I can provide that would be helpful?

**Comment by bcardarella** [comment]
Confirmed this is OK with 2.1.2-p95

**Comment by eddie-ruva** [comment]
@bcardarella I was not able to reproduce this problem with the following configuration: 

``` ruby
require 'compass/import-once/activate'

css_dir = "stylesheets"
sass_dir = "sass"

output_style = :compressed
```

``` bash
$ ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]

$ compass -v 
Compass 1.0.1 (Polaris)

$ sass -v 
Sass 3.4.2 (Selective Steve)
```

Does this look something similar to what you have?

**Comment by EricPMulligan** [comment]
compass 1.0.1 hangs whenever I have the compass-rails gem installed. As soon as I remove compass-rails, compass 1.0.1 works with no issues.

**Comment by EricPMulligan** [comment]
```
$ compass compile --trace                                                                                                                                                   1 ↵
^CInterrupt on line ["18"] of /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-rails-2.0.0/lib/compass-rails.rb:
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-rails-2.0.0/lib/compass-rails.rb:116:in `configuration'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/configuration/helpers.rb:21:in `configuration_for'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-core-1.0.1/lib/compass/configuration.rb:141:in `add_configuration'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/configuration/helpers.rb:79:in `add_project_configuration'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:25:in `configure!'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/commands/update_project.rb:41:in `initialize'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/bin/compass:44:in `call'
  /Users/ericmulligan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /Users/ericmulligan/.rbenv/versions/2.1.2/bin/compass:23:in `load'
  /Users/ericmulligan/.rbenv/versions/2.1.2/bin/compass:23:in `<main>'
```

**Comment by robertcuadra** [comment]
confirmed same issue and resolution as @ColourCodingEric

**Comment by gbrassey** [comment]
Same here: 

```
$ compass watch --trace
^CInterrupt on line ["18"] of /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-rails-2.0.0/lib/compass-rails.rb: 
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-rails-2.0.0/lib/compass-rails.rb:116:in `configuration'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/configuration/helpers.rb:21:in `configuration_for'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-core-1.0.1/lib/compass/configuration.rb:141:in `add_configuration'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/configuration/helpers.rb:79:in `add_project_configuration'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:25:in `configure!'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/commands/update_project.rb:41:in `initialize'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/bin/compass:44:in `call'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/bin/compass:23:in `load'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/bin/compass:23:in `<main>'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
  /Users/georgebrassey/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by benrudolph** [comment]
Experiencing the same issue. It's unclear to me if this is a problem with compass or compass-rails. When running compass it thinks it's in a rails app and chokes on this while loop:

https://github.com/Compass/compass-rails/blob/master/lib/compass-rails.rb#L18

**Comment by kim3er** [comment]
Confirmed the same issue and resolution.

OS X Yosemite
Ruby 2.1.2p95
Compass 1.0.1

Compass CLI would not run until I removed compass-rails from system.

**Comment by benrudolph** [comment]
This issue is now resolved for me with the new version of compass-rails 2.0.*

**Comment by mtoigo** [comment]
Uninstalling compass-rails fixed this for me as well.

**Comment by deefour** [comment]
I'm chiming in here to mention that it doesn't matter if you have `compass-rails` in your projects `Gemfile` or not. If it's in `$GEM_HOME/gems`, its going to cause `compass compile` to hang.
