### ISSUE TITLE
TypeError: no implicit conversion of Sprockets::BundledAsset into String

### ISSUE THREAD

**Issue by mcmillion** [Compass/compass#1836]
We've suddenly started getting this issue when precompiling assets. I've narrowed it down to calling `image-width` on either `sprite-path` or `sprite-file`. Oddly enough, when comparing it with other recent projects, we're not seeing the same problem. Both projects are using the same versions of sass-rails (4.0.3), compass-rails(2.0.0), and rails(4.1.4). This was previously working, but the images haven't changed in some time on the production server, so we weren't hitting the error during compilation. We found the issue once we stood up another fresh staging server and tried to push.

Both projects are using the same Sass for for the sprite mixin:

``` scss
$sprites: sprite-map('sprites/*.png');

@mixin sprite-background($name) {
  background-image: sprite-url($sprites);
  background-position: 0 ceil(nth(sprite-position($sprites, $name), 2) / 2);
  background-repeat: no-repeat;
  background-size: floor(image-width(sprite-path($sprites)) / 2) auto;
}

@mixin sprite($name) {
  @include replace-text;
  @include sprite-background($name);
  display: inline-block;
  height: floor(image-height(sprite-file($sprites, $name)) / 2);
  margin: 0;
  vertical-align: top;
  width: floor(image-width(sprite-file($sprites, $name)) /2);
}
```

The issue happens both locally when precompiling assets in production mode, or when deploying to Heroku.

Here's the full error:

```
TypeError: no implicit conversion of Sprockets::BundledAsset into String
  (in /Users/Matthew/Development/BitPivot/Freya/app/assets/stylesheets/site.scss)
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/lib/compass/sass_extensions/functions/image_size.rb:17:in `extname'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/lib/compass/sass_extensions/functions/image_size.rb:17:in `initialize'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/lib/compass/sass_extensions/functions/image_size.rb:50:in `new'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/lib/compass/sass_extensions/functions/image_size.rb:50:in `image_dimensions'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-0.12.7/lib/compass/sass_extensions/functions/image_size.rb:4:in `image_width'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/funcall.rb:113:in `_perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/operation.rb:73:in `_perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/funcall.rb:99:in `block in _perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/funcall.rb:99:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/funcall.rb:99:in `_perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/list.rb:71:in `block in _perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/list.rb:71:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/list.rb:71:in `_perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:298:in `visit_prop'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:205:in `visit_if'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (3 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block (2 levels) in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:268:in `block in visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:70:in `perform_arguments'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:263:in `visit_mixin'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `block in visit_import'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:227:in `visit_import'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/compass-rails-2.0.0/lib/compass-rails/patches/sass_importer.rb:29:in `evaluate'
/Users/Matthew/.rvm/gems/ruby-2.1.2@global/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:105:in `each'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/processed_asset.rb:16:in `initialize'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `new'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:373:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `new'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-rails-2.1.4/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/Matthew/.rvm/gems/ruby-2.1.2/gems/sprockets-rails-2.1.4/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/Matthew/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/Matthew/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by csphere** [comment]
+1

**Comment by scottdavis** [comment]
can anyone make a basic example app to recreate this?

**Comment by csphere** [comment]
Let me see what I can do.

**Comment by csphere** [comment]
Successfully reproduced the bug.  [Here's the repro project](https://github.com/csphere/CompassIssue1836).

I copied the `development.rb`, `production.rb`, and `application.rb` along with our sprite mixins exactly as they exist in the project producing the above error.

Theoretically, running `RAILS_ENV=production rake assets:precompile` should produce the error for you.

**Comment by csphere** [comment]
This just got really weird.
1. I ran `RAILS_ENV=production rake assets:precompile` and it failed with the above error as predicted.
2. I deleted the project directory completely.
3. I recloned the issue repro project.
4. Again, I ran `RAILS_ENV=production rake assets:precompile` and it **ran successfully**.
5. My sanity attribute suffered a 12 point loss.

As it happened in my terminal:

```
csphere:CompassIssue1836 csphere$ RAILS_ENV=production rake assets:precompile
I, [2014-09-24T23:11:54.224489 #57672]  INFO -- : Writing /Users/csphere/dev/BitPivot/CompassIssue1836/public/assets/sprites/icon-menu-dc70efef64d1ea5b9446738d387c451b.png
I, [2014-09-24T23:11:54.228824 #57672]  INFO -- : Writing /Users/csphere/dev/BitPivot/CompassIssue1836/public/assets/application-e8f550882a546852d0f051a79217df41.js
rake aborted!
TypeError: no implicit conversion of Sprockets::BundledAsset into String
  (in /Users/csphere/dev/BitPivot/CompassIssue1836/app/assets/stylesheets/site.scss)

csphere:BitPivot csphere$ cd .. && rm -rf CompassIssue1836
csphere:BitPivot csphere$ git clone git@github.com:csphere/CompassIssue1836.git
Cloning into 'CompassIssue1836'...
remote: Counting objects: 86, done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 86 (delta 9), reused 78 (delta 6)
Receiving objects: 100% (86/86), 18.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (9/9), done.
Checking connectivity... done.
csphere:BitPivot csphere$ cd CompassIssue1836/
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/csphere/dev/BitPivot/CompassIssue1836/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

csphere:CompassIssue1836 csphere$ RAILS_ENV=production rake assets:precompile
I, [2014-09-24T23:18:49.772516 #59178]  INFO -- : Writing /Users/csphere/dev/BitPivot/CompassIssue1836/public/assets/sprites/icon-menu-dc70efef64d1ea5b9446738d387c451b.png
I, [2014-09-24T23:18:50.108745 #59178]  INFO -- : Writing /Users/csphere/dev/BitPivot/CompassIssue1836/public/assets/application-6bb8ee07463765838690b7121322a435.js
I, [2014-09-24T23:18:50.317046 #59178]  INFO -- : Writing /Users/csphere/dev/BitPivot/CompassIssue1836/public/assets/application-7c93a230a405a71304d324b1aa7fd870.css
csphere:CompassIssue1836 csphere$
```

Is this real life?

**Comment by csphere** [comment]
I tried deleting and recloning the offending repo as well on the off-chance the same thing would happen, and `RAILS_ENV=production rake assets:precompile` failed with the same error.

**Comment by scottdavis** [comment]
Thanks I'll take a look!

**Comment by bobbus** [comment]
:+1:
