### ISSUE TITLE
Change block raise an execption: undefined method 'to_tree'

### ISSUE THREAD

**Issue by philgruneich** [Compass/compass#1851]
Sass 3.4.5 (Selective Steve)
Compass 1.1.0.alpha.3 (Polaris)
ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]

Could be similar to https://github.com/Compass/compass/issues/1641

```
[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Backtrace:
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:184:in `tree'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:125:in `each'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:125:in `any?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:81:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:211:in `block in update_stylesheets'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:209:in `each'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:469:in `on_file_changed'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/lib/sass/plugin/compiler.rb:328:in `block in watch'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/listener.rb:252:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/listener.rb:252:in `on_change'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/adapters/polling.rb:48:in `call'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/adapters/polling.rb:48:in `poll_changed_directories'
    /Library/Ruby/Gems/2.0.0/gems/sass-3.4.5/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

**Comment by luke-rooster** [comment]
I'm also getting this same issue.

Not sure if it is anything to do with this but I am using global variables via the import feature (one main file pulling in all SCSS files /w variables declared at top, used throughout) sometimes it will flag that  x.scss cannot find $v.

Issue is fixed if I cancel the current watch command and re-run it

**Comment by seminice** [comment]
Any news with this issue? I'm getting the same too.

**Comment by earl3s** [comment]
I'm also getting this error on version 1.0.1.  Any ideas on it?

**Comment by byCedric** [comment]
Still an issue on 1.0.3...

**Comment by benjarwar** [comment]
Also reporting the issue on 1.0.3.

**Comment by KristobalJunta** [comment]
Same trouble, v1.0.3 too

**Comment by sherizan** [comment]
same here
Compass 1.0.3 (Polaris)

**Comment by tomasdev** [comment]
:+1: 

A fix is terminating your compass watch and starting it back again.

**Comment by joedaniels** [comment]
@tomasdev Not much of a fix since you have to be constantly terminating and starting compass over and over again.

**Comment by seminice** [comment]
I agree wtih @joedaniels

**Comment by benjarwar** [comment]
I also agree with @joedaniels.

**Comment by krstffr** [comment]
I also agree with @joedaniels.

**Comment by Jones-S** [comment]
same here. 1.0.3

**Comment by honucreative** [comment]
Getting the same problem.

**Comment by duckumu** [comment]
I've also been having this issue for months. I stop Compass and run the watch command again to get everything working but... yeah.

ETA: Thought it worth mentioning that the only Compass frameworks I have installed are:
compass
sassy-maps
breakpoint

**Comment by Antoinebr** [comment]
Same here :/

**Comment by mcclaskiem** [comment]
Getting this error as well.

Using:
Bourbon
Bourbon-Neat
Custom Silent Classes and mixins/vars

Any word on a fix?

**Comment by voidstate** [comment]
Also having this issue.

**Comment by rebdev** [comment]
Same...

**Comment by ktoh** [comment]
Ditto...

**Comment by petemolinero** [comment]
Same issue for me.

**Comment by ccpotter** [comment]
Same issue here. I have multiple projects running compass watch, some local, some on network drives and this seems to only occur when watching files on a network drive. Fixed by resaving the sass file but frustrating none the less. Another thing that I have done is changed where the cache is stored by modifying the config.rb for my network projects. cache_path = 'C:/temp/PROJECTNAME/.sass-cache'

**Comment by dynamicdan** [comment]
No joy?
Fixes?

**Comment by jonlambert** [comment]
Same here.

**Comment by jstoller** [comment]
I've been having this problem for a while now and thought it was me. :-/

I'm using the following gems:
- breakpoint (2.5.0)
- bundler (1.9.9)
- chunky_png (1.3.4)
- color-schemer (0.2.8)
- compass (1.0.3)
- compass-blend-modes (0.0.2)
- compass-core (1.0.3)
- compass-import-once (1.0.5)
- compass-normalize (1.5)
- ffi (1.9.8)
- modular-scale (2.0.6)
- multi_json (1.11.0)
- rb-fsevent (0.9.5)
- rb-inotify (0.9.5)
- sass (3.4.14)
- sassy-maps (0.4.0)
- singularitygs (1.6.2)
- toolkit (2.9.0)

**Comment by webilhan** [comment]
Same error for me

**Comment by azclub** [comment]
Same error ....

**Comment by tsi** [comment]
Same here too...

**Comment by artursopelnik** [comment]
Same error here …

**Comment by Haikson** [comment]
Same error too...

**Comment by gcasalett** [comment]
Just keeping this alive. This issue started out of the blue a couple of weeks ago. Only significant software change I can think of is I upgraded to Adobe Suite CC 2015.

Ruby v. 2.2.2p95
Sass v.  4.3.13
Compass v. 1.0.3

**Comment by japascal** [comment]
same here

**Comment by SedueRey** [comment]
lol but ... same here :)

**Comment by seminice** [comment]
solved by not using compass.

**Comment by jstoller** [comment]
It seems to be Compass watch that's causing the problem here. I started using Gulp to watch my files and trigger a compass compile and that works fine.

**Comment by striky1** [comment]
same here

compass (1.0.3)
sass (3.4.13)

**Comment by lutoma** [comment]
Getting this too from time to time after saving a file.

**Comment by x1unix** [comment]
I aslo have this problem. I think that this is a Compass bug.

**Comment by ItIsInspiring** [comment]
i have the same problem.
My "solution" is to make compass restart again with "ctrl"+"c" and "o".
When it restarts, it works again.

**Comment by Kwaadpepper** [comment]
Also have this bug, you may do : 
while :; do compass compile; sleep 2; done

**Comment by fabiofidanza** [comment]
Happening randomly here too
"compass","1.0.1"
"sass","3.4.18"

Only fix is to kill and restart the watcher process.

**Comment by JamesVanWaza** [comment]
Using compass and compass-import-once is not recommended to use them at the same time, Only use Compass.

**Comment by petulla** [comment]
Same here..

**Comment by ymondirNm** [comment]
if you have imports, you can save another file(add and remove a space) and it works, it's not a fix but still better than restart the watcher

**Comment by JamesVanWaza** [comment]
@fabiofidanza Are you still seeing the problem, if so, please post your gruntfile so I can see what's wrong as well as a list of node_modules you are using.

**Comment by fabiofidanza** [comment]
@jgacuca567 I'm using a plain old compass watch, launched via nohup:

`nohup bundle exec compass watch >compass.log &`

here are the Gems that are used in one of the projects where I experience the problem:

```
chunky_png (1.3.4)
compass (1.0.1)
  chunky_png (~> 1.2)
  compass-core (~> 1.0.1)
  compass-import-once (~> 1.0.5)
  rb-fsevent (>= 0.9.3)
  rb-inotify (>= 0.9)
  sass (>= 3.3.13, < 3.5)
compass-core (1.0.3)
  multi_json (~> 1.0)
  sass (>= 3.3.0, < 3.5)
compass-import-once (1.0.5)
  sass (>= 3.2, < 3.5)
ffi (1.9.10)
multi_json (1.11.2)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
  ffi (>= 0.5.0)
sass (3.4.15)
```

Thanks

**Comment by JamesVanWaza** [comment]
@fabiofidanza I guess, for me I have been using NPM Modules, see My gist file, see how I have setup file. As of now when I run sudo grunt, no errors from compass are found. 

https://gist.github.com/jgacuca567/143754cd4590df7f00fd

**Comment by imme-emosol** [comment]
My guess would be that there's something wrong on line 80 in
/var/lib/gems/2.1.0/gems/sass-3.4.19/lib/sass/plugin/staleness_checker.rb
On that line the importer should be set to the given option filesystem_importer if it's nil .
The importer however seems to  end up as nil at /var/lib/gems/2.1.0/gems/sass-3.4.19/vendor/listen/lib/listen/adapter.rb :299 .

The other possibility is that somehow importer gets reset to nil.
Which seems to be able to be because of the thread as mentioned in https://github.com/guard/listen/issues/219 .
On a short test this Thread-timing-issues seems to fix the issue for me.
I changed the DEFAULT_LATENCY on line 22 from 0.25 to 2 in the file :
/var/lib/gems/2.1.0/gems/sass-3.4.19/vendor/listen/lib/listen/adapter.rb .

**Comment by otygblodhemn** [comment]
Same issue since today. Not viewed before.

autoprefixer-rails (6.0.3)
bigdecimal (1.2.6)
bootstrap-sass (3.3.5.1)
chunky_png (1.3.4)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
execjs (2.6.0)
ffi (1.9.10 x86-minggw32)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
multi_json (1.11.2)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rdoc (4.2.0)
sass (3.4.19)
test-unit (3.0.8)

**Comment by bnomei** [comment]
same... 
compass (1.0.3),
compass-core (1.0.3), 
compass-import-once (1.0.5), 
susy (2.2.6)

**Comment by Kansuler** [comment]
I also experience this problem, quite often..

**Comment by kyleridolfo** [comment]
Has anyone found a solution for this?

**Comment by jstoller** [comment]
@yaykyle Yes. Don't use compass watch. ;-)  I've been using Gulp with the [Simple Compass](https://github.com/Snugug/gulp-simple-compass) gulp task to compile my sass. It was relatively easy to set up, has provided more flexibility, and worked problem free for some time now.

If anyone's interested, the simple gulp file I've started with is as follows:

``` javascript
/*!
 * gulp
 * $ npm install --save-dev gulp gulp-simple-compass
 */

// Load plugins
var gulp = require('gulp'),
    compass = require('gulp-simple-compass');

// Styles
gulp.task('styles', function() {
  gulp.src('sass/*.scss')
    .pipe(compass());
});

// Watch
gulp.task('watch', function() {

  // Watch config.rb and recompile CSS on change.
  gulp.watch('config.rb', ['styles']);

  // Watch .scss files and recompile CSS on change.
  gulp.watch('sass/**/*.scss', ['styles']);

});

// Default task
gulp.task('default', function() {
    gulp.start('styles', 'watch');
});
```

This not only recompiles my sass when I edit a .scss file, as compass watch did, but also when I edit my config.rb file, which has been really handy.

**Comment by sidouglas** [comment]
I get this error too. The Gulp solution requires bundler and more complexity, more configuration. 
Just fix compass watch...

**Comment by MykeArgyle** [comment]
Just got the error using watch. Quit watch and restarted, things worked again. Not ideal but it works to get rid of errors.

**Comment by t-wales** [comment]
No fix in sight?

**Comment by caedmonm** [comment]
Same here... driving me a little crazy.

**Comment by ycwong1987** [comment]
still no answer?

**Comment by ItsLemmy** [comment]
this issue needs more love.

**Comment by marychris** [comment]
Same issue here with compass watch.
Here is my gemfile:
`source "https://rubygems.org"

gem 'sass', "3.4.21"
gem 'sass-globbing', ">= 1.1.1"
gem 'compass', "1.0.3"
gem 'bootstrap', "4.0.0.alpha3"`

Hope someone comes up with a better solution than stop using compass :D

**Comment by amylashley** [comment]
I am also still having this problem. I'm new to compass..it worked fine for a day, but now it's total hell. I have to restart it constantly. UGH!!!! I'm using it on OSX 10.10.x and it happens via the app or command line.

**Comment by jblom** [comment]
Just got this problem after I started using multiple sub folders to differentiate between default themes and custom themes... Restarting all the time does defeat the purpose of the watch... Also not fond to start using that Gulp solution with already a million packaging things in place

**Comment by kostiantyn-petlia** [comment]
2014-2016?! Two years? And people restarting Compass.app and the bug not fixed? Hmm... It's true: "this issue needs more love" & the attention of developers!

**Comment by JamesVanWaza** [comment]
@amylashley @jblom @artfulcat 

**`Compass`** is no longer supported

**Comment by shehi** [comment]
I have been using Compass for ages, without any problems. Now randomly getting this very error:

```
[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Did you mean?  to_r
Backtrace:
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:184:in `tree'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:125:in `any?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:211:in `block in update_stylesheets'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:209:in `each'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:473:in `on_file_changed'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/lib/sass/plugin/compiler.rb:331:in `block in watch'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/listener.rb:252:in `on_change'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapter.rb:323:in `poll_changed_directories'
    /var/lib/gems/2.3.0/gems/sass-3.4.22/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

Is Compass leaving some kind of config file in Home directory (Ubuntu)? I started having this right after I reinstalled OS (I still am using the same Homedir with old contents). If Compass has some config file left in Homedir, I will try to removing it.

**Comment by microacup** [comment]
same

**Comment by wdehaes** [comment]
same problem

**Comment by leonelcbraz** [comment]
Same...

Version:

=> compass -v
Compass 1.0.3 (Polaris)

Error:

[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Backtrace:
	/Users/leonelcostabraz/.rvm/gems/ruby-2.2.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:184:in `tree'
	/Users/leonelcostabraz/.rvm/gems/ruby-2.2.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
	/Users/leonelcostabraz/.rvm/gems/ruby-2.2.0/gems/sass-3.4.22/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
(...)

**Comment by ItsLemmy** [comment]
Compass is **no longer supported**, don't expect a fix.
Read more on the front page : https://github.com/Compass/compass

Either move on or implement your own watch script using 'fswatch'.

**Comment by sajjadalis** [comment]
Wow. it's been over 2 years and still no fix or even idea about why it happens.
I have this issue for few months. Earlier it happens once or twice but today its happening again and again. Glad i looked it up. I guess have to move on.

**Comment by ranismk** [comment]
I got this error today and was looking for a fix, so I reached here. Clearing '.sass-cache' folder did the trick for me!

**Comment by quickplaymobile** [comment]
Got this bug today, I was looking for a fix, I'm impressed that it's been almost 3 years since this was reported for the first time.

**Comment by earl3s** [comment]
Never going to be fixed now that it's a deprecated library.  Peace out Compass, it's been real.

**Comment by filipedanielpires** [comment]
This was happening to me, because I have one folder with accent characters, I renamed that folder with non accented characters and everything got back to normal.

**Comment by mrcleanandfresh** [comment]
@earl3s Is there a recommendation of what to use instead of compass? I have some legacy code hanging on to this library.

**Comment by earl3s** [comment]
I'd try node-sass.  Works well for us.

**Comment by mateostabio** [comment]
**FOUND THE FIX** 
My new website root folder was called **New_Website™**
I renamed it to **New Website** without the underscore and without the ™. 
The problem for me was the folder name contained a special character or accent character. You gotta remove them!
I then deleted my .sass-cache folder, and stoped compass using Ctrl-C. I started Compass watch again... And BOOM! 
It works perfectly .

Thank you @filipedanielpires for pointing the accent characters out. 🥇
