### ISSUE TITLE
TypeError: superclass mismatch for class Literal?

### ISSUE THREAD

**Issue by ee99ee** [Compass/compass#1856]
I'm trying to compile a SASS file with Compass and I keep getting an error: "TypeError: superclass mismatch for class Literal." I have no idea what to do. This error only occurs on my Jenkins CI box (Ubuntu 14.04) where I'm building the project, but on my dev box (OS X) it's fine.

The specific error with trace is:

```
$ sass assets/my_site/styles/sass/default.scss assets/my_site/styles/default.css --cache-location .tmp/.sass-cache --style expanded --compass --trace
/usr/lib/ruby/vendor_ruby/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
    from /usr/lib/ruby/vendor_ruby/sass/script/literal.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /usr/lib/ruby/vendor_ruby/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/vendor_ruby/compass/sass_extensions.rb:9:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/vendor_ruby/compass.rb:5:in `block in <top (required)>'
    from /usr/lib/ruby/vendor_ruby/compass.rb:4:in `each'
    from /usr/lib/ruby/vendor_ruby/compass.rb:4:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:237:in `load_compass'
    from /var/lib/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:48:in `process_result'
    from /var/lib/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/base.rb:52:in `parse'
    from /var/lib/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/base.rb:19:in `parse!'
    from /var/lib/gems/2.1.0/gems/sass-3.4.6/bin/sass:13:in `<top (required)>'
    from /usr/local/bin/sass:23:in `load'
    from /usr/local/bin/sass:23:in `<main>'
```

I've tried this with Ruby 1.9, 2.0 and 2.1. I updated my gems and am still having this issue. Here are the gems I have installed:

```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
chunky_png (1.3.2)
compass (1.1.0.alpha.3)
compass-core (1.1.0.alpha.3)
compass-import-once (1.0.5)
dogapi (1.11.0)
ffi (1.9.6)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
multi_json (1.10.1)
psych (2.0.5)
rake (10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.1.0)
sass (3.4.6)
sassy-buttons (0.2.6)
test-unit (2.1.2.0)
```

And some Ruby info:

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux-gnu]

$ irb
irb(main):001:0> RUBY_VERSION
=> "2.1.2"
```

I'm at a loss of what to do...

**Comment by ee99ee** [comment]
Btw, I also tried Compass 1.0.1 and it's doing the same thing. It also throws the same error if I use "-r compass" instead of "--compass", but I guess those are the same.

Also, this error occurs even on an empty file (touch foo.scss then try to compile that)... so it's nothing in particular to my specific SASS file.

**Comment by ee99ee** [comment]
Anyone?

**Comment by ebbe-minecraft** [comment]
Im having the exact same issue. Sorry I dont have a answer if I find it I will get back to you.

**Comment by marcusamargi** [comment]
same issue for me too

**Comment by gkorland** [comment]
any solution?

**Comment by mkrishtopa** [comment]
same issue

**Comment by staab** [comment]
Same here

**Comment by staab** [comment]
I was able to solve this problem by using rvm to install ruby `2.2.0p37 (2015-01-26 revision 49409) [x86_64-linux]`. Once I did that, I followed the directions to install compass [here](http://compass-style.org/install/), and it worked fine. 2.2.0 straight up didn't work. Hope that helps.

**Comment by ee99ee** [comment]
Having this issue again... started appearing out of nowhere. So annoying!!

`$ sass -v
Sass 3.4.13 (Selective Steve)
$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
$ compass -v
Compass 1.0.3 (Polaris)`

**Comment by ee99ee** [comment]
Update: I ended up removing all sass and compass gems and reinstalling... works now. Same versions, though. No idea what was going on...
