### ISSUE TITLE
Error with compass watch

### ISSUE THREAD

**Issue by KabbAmine** [Compass/compass#1877]
Hi.

I have an error every time using `compass watch`

```
compass watch --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
NoMethodError on line ["398"] of /home/k-bag/.rvm/gems/ruby-2.1.4/gems/sass-3.4.0/lib/sass/plugin/compiler.rb: undefined method `join' for #<Thread::Queue:0x0000000371e000>
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:398:in `each'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:398:in `listen_to'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/sass-3.4.0/lib/sass/plugin/compiler.rb:334:in `watch'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/sass_compiler.rb:46:in `watch!'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/commands/watch_project.rb:41:in `perform'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/bin/compass:44:in `call'
  /home/k-bag/.rvm/gems/ruby-2.1.4/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /home/k-bag/.rvm/gems/ruby-2.1.4/bin/compass:23:in `load'
  /home/k-bag/.rvm/gems/ruby-2.1.4/bin/compass:23:in `<main>'
  /home/k-bag/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
  /home/k-bag/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

I can see that is related to `sass` but even using an old `sass` version, I still have the same error. 
### Configuration

```
Xubuntu 14.04
Sass 3.4.7
Compass 1.0.1
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]
```

**Comment by KabbAmine** [comment]
Ok, no more error with `ruby 1.9.3` and `watch` is working as usually.

Issue closed then.
