### ISSUE TITLE
cannot load such file -- compass/core

### ISSUE THREAD

**Issue by johnteakdigital** [Compass/compass#1891]
Hey I'm unable to get compass working correctly on a fresh install. I've tried installing and uninstalling both compass and sass but nothing seems to work. Any direction would be great. Thank you!

ruby v 2.0
gem v 2.4.5
sass 3.4.9
compass 1.0.1
on mac osx 10.9.4

Here's the error I get when I run `$ compass -v` or any compass command

```
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- compass/core (LoadError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/lib/compass.rb:14:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/lib/compass.rb:13:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/lib/compass.rb:13:in `<top (required)>'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/bin/compass:20:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/2.0.0/gems/compass-1.0.1/bin/compass:19:in `<top (required)>'
    from /usr/bin/compass:23:in `load'
    from /usr/bin/compass:23:in `<main>'
```

**Comment by osj2507** [comment]
I just began getting this and can't seem to figure out what is going wrong, did you ever solve this issue?
