### ISSUE TITLE
Listen warning - undefined method `to_tree' for nil:NilClass

### ISSUE THREAD

**Issue by eft** [Compass/compass#1908]
I am also seeing the error reported in #1868 and #1873 (see backtrace below).

Steps to reproduce:
- reference same import from two different .scss files.
- run compass complile/watch.
- both .css files are generated.
- edit and save leaf partial - only one of the css files is regenerated.
- if an intermediate partial is edited and saved and then the leaf partial is edited and saved then only the one css files is regenerated.  If using compass watch, the exception below is triggered.
- [forcing an import](https://github.com/Compass/compass/tree/stable/import-once#forcing-an-import) does not seem to help.

---

compass (1.0.1)
compass-core (1.0.1)
compass-import-once (1.0.5)
ruby-2.0.0-p451
node.js 0.10.35

---

```
[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Backtrace:
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:184:in `tree'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:125:in `each'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:125:in `any?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:81:in `call'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:211:in `block in update_stylesheets'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:209:in `each'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:470:in `on_file_changed'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/lib/sass/plugin/compiler.rb:328:in `block in watch'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/listener.rb:252:in `call'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/listener.rb:252:in `on_change'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/adapter.rb:254:in `call'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/adapter.rb:323:in `poll_changed_directories'
        /foo/platforms/au201412292333/sites/all/themes/bar/.vendor/bundle/ruby/2.0.0/gems/sass-3.4.9/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

**Comment by chiva05** [comment]
thanks @eft  i will

**Comment by ivanhercaz** [comment]
Thanks for that report @eft!

**Comment by tommmyy** [comment]
+1
