### ISSUE TITLE
Copied project on different location causes error

### ISSUE THREAD

**Issue by GMBrian** [Compass/compass#1922]
I was working locally on a purely HTML+CSS project for a day or 2 after moving it into a theme for WordPress. But after I moved the entire project folder to the theme and tried to make compass watch that new folder it causes an error. I've tried copying the project to a different new location and watch it and that works fine.

I'm working on a beta that I had to request over email from 7 days ago. I really hope a new version is coming out soon, this beta version also needs to restart every 15mins because it just stops working without notice, but I don't get an error from that.

The paths:
Original HTML+CSS project: C:\xampp\htdocs\project1
WordPress project (causes error):  C:\xampp\htdocs\project1wp\wp-content\themes\project1\assets

---

My config:
require 'compass/import-once/activate'
# Require any additional compass plugins here.

http_path = "../../"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "js"
# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

relative_assets = true
# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false

line_comments = true

preferred_syntax = :scss

---

This is  the report: 
No such process - No message available
org/jruby/RubyFile.java:613:in `chmod'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/util.rb:1257:in`atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/util.rb:1255:in`atomic_create_and_write_file'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/cache_stores/filesystem.rb:39:in `_store'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/cache_stores/base.rb:51:in`store'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/cache_stores/chain.rb:19:in `store'
org/jruby/RubyArray.java:1613:in`each'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/cache_stores/chain.rb:19:in `store'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/engine.rb:404:in`_to_tree'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/engine.rb:299:in `to_tree'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:183:in`compute_dependencies'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/tree/node.rb:193:in `each'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/tree/node.rb:192:in`each'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyArray.java:1613:in`each'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyEnumerable.java:512:in`grep'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:179:in `compute_dependencies'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:153:in`dependencies'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:169:in`dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:129:in`dependencies_stale?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:169:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in`any?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:169:in`dependency_updated?'
org/jruby/RubyProc.java:271:in `call'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:85:in`stylesheet_modified_since?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/staleness_checker.rb:73:in `stylesheet_needs_update?'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/compiler.rb:211:in`update_stylesheets'
org/jruby/RubyArray.java:1613:in `each'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/compiler.rb:209:in`update_stylesheets'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/sass-3.4.9/lib/sass/plugin/compiler.rb:293:in `watch'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/compass-1.0.1/lib/compass/sass_compiler.rb:46:in`watch!'
C:/Program Files (x86)/compass.app/lib/ruby/compass_1.0/compass-1.0.1/lib/compass/commands/watch_project.rb:41:in `perform'
file:/C:/Program Files (x86)/compass.app/compass-app.jar!/app_watcher.rb:12:in`watch!'
file:/C:/Program Files (x86)/compass.app/compass-app.jar!/ui/tray.rb:447:in `watch'

**Comment by GMBrian** [comment]
Anything on this issue? It's hard to work around at the moment.

**Comment by SeanLatimer** [comment]
I'm getting the exact same issue, on Version 1.29
