### ISSUE TITLE
undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by r007** [Compass/compass#1938]
I have a problem with compass after updating. I use middleman in my project and when I do `middleman build --verbose`, I get this result:

``` console
       error  library/stylesheets/themes/aqua-theme.css
undefined method `start_with?' for nil:NilClass
/var/lib/gems/1.9.1/gems/compass-core-1.1.0.alpha.3/lib/compass/core/http_util.rb:17:in `expand_url_path'
/var/lib/gems/1.9.1/gems/compass-core-1.1.0.alpha.3/lib/compass/core/http_util.rb:45:in `compute_relative_path'
/var/lib/gems/1.9.1/gems/compass-core-1.1.0.alpha.3/lib/compass/core/sass_extensions/functions/urls.rb:25:in `stylesheet_url'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/script/tree/funcall.rb:139:in `_perform'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/script/tree/node.rb:50:in `perform'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:299:in `block (2 levels) in visit_if'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:299:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:299:in `block in visit_if'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:298:in `visit_if'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:363:in `block (4 levels) in visit_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:363:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:363:in `block (3 levels) in visit_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:363:in `block (2 levels) in visit_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:358:in `block in visit_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:98:in `block in with_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:98:in `with_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:346:in `visit_mixin'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:88:in `block in with_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:88:in `with_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:88:in `block in with_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:88:in `with_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:52:in `map'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:157:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/visitors/perform.rb:8:in `visit'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/root_node.rb:36:in `css_tree'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/tree/root_node.rb:20:in `render'
/var/lib/gems/1.9.1/gems/sass-3.4.12/lib/sass/engine.rb:268:in `render'
/var/lib/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `block in render'
/var/lib/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in `with_import_scope'
/var/lib/gems/1.9.1/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
/var/lib/gems/1.9.1/gems/sprockets-sass-1.3.1/lib/sprockets/sass/sass_template.rb:53:in `evaluate'
/var/lib/gems/1.9.1/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:197:in `block in evaluate'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `each'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/context.rb:194:in `evaluate'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `new'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:374:in `block in build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:373:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `new'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:377:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/environment.rb:75:in `find_asset'
/var/lib/gems/1.9.1/gems/sprockets-2.12.3/lib/sprockets/server.rb:47:in `call'
/var/lib/gems/1.9.1/gems/middleman-sprockets-3.4.1/lib/middleman-sprockets/environment.rb:226:in `call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
/var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:153:in `call'
/var/lib/gems/1.9.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
/var/lib/gems/1.9.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
/var/lib/gems/1.9.1/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:255:in `render_to_file'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:221:in `build_resource'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:186:in `each'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:186:in `execute!'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:128:in `invoke!'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/actions.rb:94:in `action'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli/build.rb:70:in `build'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli.rb:72:in `method_missing'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/lib/middleman-core/cli.rb:20:in `start'
/var/lib/gems/1.9.1/gems/middleman-core-3.3.9/bin/middleman:18:in `<top (required)>'
/usr/local/bin/middleman:23:in `load'
/usr/local/bin/middleman:23:in `<main>'
```

I'm not sure whose problem is it, but it occurs only in 1.1.0.alpha.3. In 1.0.3 everything is working like a charm. I assume that it's strictly compass problem.

**Comment by lachlanmcdonald** [comment]
What are the contents of `library/stylesheets/themes/aqua-theme.css`?

**Comment by r007** [comment]
This file is huge, with dozens of `@import`. 10000 lines of code and 520 Kb total. Afraid it will take forever to debug this file line by line. So I temporarily switched to 1.0.3. I plan to locate problem later.
