### ISSUE TITLE
LoadError on line ["179"] of ~/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/data.rb: cannot load such file -- compass/import-once/activate

### ISSUE THREAD

**Issue by miguelmota** [Compass/compass#1940]
``` bash
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
$ compass -v
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2015 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
$ compass watch --trace
LoadError on line ["179"] of /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/data.rb: cannot load such file -- compass/import-once/activate
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/data.rb:179:in `require'
  /Users/moogs/Dropbox/Development/acorns/d3-graphs/projection-graph/public/config.rb:1:in `get_binding'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `eval'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `parse_string'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `open'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `_parse'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:207:in `with_defaults'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:19:in `configuration_for'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:69:in `add_project_configuration'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:25:in `configure!'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/update_project.rb:41:in `initialize'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:44:in `call'
  /Users/moogs/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /Users/moogs/.rvm/gems/ruby-2.2.0/bin/compass:23:in `load'
  /Users/moogs/.rvm/gems/ruby-2.2.0/bin/compass:23:in `<main>'
  /Users/moogs/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  /Users/moogs/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

`config.rb`

``` ruby
require 'compass/import-once/activate'
# Require any additional compass plugins here.

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "css"
sass_dir = "sass"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false


# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass
```

**Comment by cjmosure** [comment]
Getting this as well

```
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.3)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
LoadError on line ["179"] of /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-core-1.0.3/lib/compass/configuration/data.rb: cannot load such file -- compass/import-once/activate
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-core-1.0.3/lib/compass/configuration/data.rb:179:in `require'
  /Users/christophermosure/Sites/rubes/config.rb:1:in `get_binding'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `eval'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `parse_string'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:15:in `block in _parse'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `open'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `_parse'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:207:in `with_defaults'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/file_data.rb:6:in `new_from_file'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:19:in `configuration_for'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/configuration/helpers.rb:69:in `add_project_configuration'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/commands/project_base.rb:25:in `configure!'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/commands/project_base.rb:15:in `initialize'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/commands/update_project.rb:41:in `initialize'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `new'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:42:in `perform!'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/bin/compass:44:in `call'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/bin/compass:23:in `load'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/bin/compass:23:in `<main>'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
  /Users/christophermosure/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by anujaware** [comment]
:+1:  Getting same error.

**Comment by oskarszura** [comment]
I have similar issue when deploying my project to heroku - http://stackoverflow.com/questions/35315127/heroku-gulp-compass-deployment-issue

**Comment by ghost** [comment]
Any help? I'm stuck on it too. I'm trying to recompile an old project via Gulp.
Tried many times - with no results - in:
- Reinstall Ruby with RVM (from version 2.1 to 2.6);
- Reinstall SASS (v. 3.3);
- Reinstall Compass with ```compass-import-once``` gem;

Running on OS X 10.13.6.

**EDIT:**

A possible solution. It worked for me:

https://stackoverflow.com/questions/55972270/compass-failed-error-on-compiling-sass-via-gulp/56001818#56001818
