### ISSUE TITLE
Not working in Ubuntu [Errno::ENOENT ]

### ISSUE THREAD

**Issue by ghost** [Compass/compass#1955]
You'd think this would install `compass`:

```
gem install compass
```

But , here is what I got when checking if it worked:

```
vagrant@vagrant-ubuntu-trusty-32:/vagrant/attache/client$ compass -v --trace
Errno::ENOENT on line ["25"] of /usr/lib/ruby/vendor_ruby/compass/version.rb: No such file or directory - /usr/lib/ruby/vendor_ruby/compass/../../VERSION.yml
  /usr/lib/ruby/vendor_ruby/compass/version.rb:25:in `read_version'
  /usr/lib/ruby/vendor_ruby/compass/version.rb:13:in `version'
  /usr/lib/ruby/vendor_ruby/compass/commands/print_version.rb:59:in `long_output_string'
  /usr/lib/ruby/vendor_ruby/compass/commands/print_version.rb:94:in `execute'
  /usr/lib/ruby/vendor_ruby/compass/commands/default.rb:46:in `execute'
  /usr/lib/ruby/vendor_ruby/compass/exec/sub_command_ui.rb:43:in `perform!'
  /usr/lib/ruby/vendor_ruby/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/bin/compass:30:in `block in <main>'
  /usr/bin/compass:44:in `call'
  /usr/bin/compass:44:in `<main>'
vagrant@vagrant-ubuntu-trusty-32:/vagrant/attache/client$ 

```

I actually did see [this](http://stackoverflow.com/questions/21079342/cant-use-compass-after-installing-it), but it did not help a bit.

Any thoughts?

**Comment by gbrlsepulveda** [comment]
+1

**Comment by ghost** [comment]
I had forgotten to close this. 
@gbrlsepulveda => [This](http://stackoverflow.com/questions/28890719/how-to-install-a-gem-globally-without-sudo-using-rbenv/28912501#28912501) may be able to help you.
