### ISSUE TITLE
 compass watch error : No such file or directory @ realpath_rec

### ISSUE THREAD

**Issue by mukiwu** [Compass/compass#1964]
I can run `compass create` and `compass compile`, but when I run `compass watch`, there has something wrong, here is the wrong message:

![2015-04-03 11 34 14](https://cloud.githubusercontent.com/assets/3794103/6984314/18ebcebc-da5a-11e4-8709-5c65408e9641.png)

`compass watch -trace` : 

```
$ compass watch --trace                                                                         [23:34:07]
>>> Compass is watching for changes. Press Ctrl-C to Stop.
Errno::ENOENT on line ["50"] of /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen/listener.rb: No such file or directory @ realpath_rec - /Users/muki/.compass/extensions/muki-master/stylesheets
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen/listener.rb:50:in `realpath'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen/listener.rb:50:in `block in initialize'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen/listener.rb:50:in `map'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen/listener.rb:50:in `initialize'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen.rb:70:in `new'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen.rb:70:in `_add_listener'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/listen-2.7.9/lib/listen.rb:27:in `to'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/plugin/compiler.rb:393:in `block in create_listener'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/plugin/compiler.rb:392:in `map'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/plugin/compiler.rb:392:in `create_listener'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/sass-3.4.13/lib/sass/plugin/compiler.rb:327:in `watch'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:44:in `call'
  /Users/muki/.rvm/gems/ruby-2.2.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /Users/muki/.rvm/gems/ruby-2.2.0/bin/compass:23:in `load'
  /Users/muki/.rvm/gems/ruby-2.2.0/bin/compass:23:in `<main>'
  /Users/muki/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  /Users/muki/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
FAIL: 1
```

my version:
- Sass 3.4.13 
- Compass 1.0.3 (Polaris)

I don't know how to solve this situation, does anyone have any idea for that ? thanks !

**Comment by verdeandrea** [comment]
@mukiwu I have the same error. How did you solved that?

**Comment by verdeandrea** [comment]
Ok, i solved uninstalling listen
`$sudo gem uninstall listen`
and then installing it again
