### ISSUE TITLE
Errno::EACCES on line ["1144"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied

### ISSUE THREAD

**Issue by mrsinguyen** [Compass/compass#1989]
I have error when run

```
compass watch
```

Full log

```
Errno::EACCES on line ["1144"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/.listen_test
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1144:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1144:in `rescue in block in touch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1140:in `block in touch'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1138:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1138:in `touch'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:231:in `works?'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:190:in `block in usable_and_works?'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:190:in `each'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:190:in `all?'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:190:in `usable_and_works?'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:57:in `block in select_and_initialize'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:55:in `each'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/adapter.rb:55:in `select_and_initialize'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/listener.rb:291:in `initialize_adapter'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/listener.rb:283:in `setup'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen/listener.rb:52:in `start'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/vendor/listen/lib/listen.rb:29:in `to'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:393:in `block in create_listener'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:392:in `map'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:392:in `create_listener'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:327:in `watch'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:44:in `call'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /usr/bin/compass:23:in `load'
  /usr/bin/compass:23:in `<main>'
```

And Gemlog packages

```
Using addressable 2.3.8
Using sass 3.4.15
Using sassy-maps 0.4.0
Using breakpoint 2.5.0
Using chunky_png 1.3.4
Using coderay 1.1.0
Using multi_json 1.11.1
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.9
Using rb-inotify 0.9.5
Using compass 1.0.3
Using compass-normalize 1.5
Using compass-rgbapng 0.2.1
Using compass-validator 3.0.1
Using css_parser 1.3.6
Using eventmachine 1.0.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using formatador 0.2.5
Using listen 3.0.0
Using lumberjack 1.0.9
Using nenv 0.2.0
Using shellany 0.0.1
Using notiffany 0.0.6
Using method_source 0.8.2
Using slop 3.6.0
Using pry 0.10.1
Using thor 0.19.1
Using guard 2.12.7
Using guard-compass 1.1.0
Using guard-compat 1.2.1
Using guard-livereload 2.4.0
Using guard-shell 0.7.1
Using oily_png 1.2.0
Using rb-fchange 0.0.6
Using sass-globbing 1.1.1
Using singularitygs 1.6.2
Using susy 2.2.5
Using toolkit 2.9.0
Using yajl-ruby 1.2.1
Using bundler 1.10.5
```

Ruby version:

```
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

on MacOS 10.10.3

**Comment by JamesVanWaza** [comment]
@mrsinguyen Run it as sudo compass watch.

**Comment by mrsinguyen** [comment]
I have tried but fail, below is error

```
[12:05][mrsinguyen@Nguyen:~/Workspaces/project(master)]$ compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/vt-theme.no-query.css
    write css/vt-theme.styles.css
Errno::EACCES on line ["1144"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/.listen_test
Run with --trace to see the full backtrace
[12:05][mrsinguyen@Nguyen:~/Workspaces/project(master)]$ sudo compass watch
Password:
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/vt-theme.no-query.css
    write css/vt-theme.styles.css
NoMethodError on line ["402"] of /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb: undefined method `start' for #<Thread:0x007fd4fc81f5f0 sleep>
Run with --trace to see the full backtrace
[12:05][mrsinguyen@Nguyen:~/Workspaces/project(master)]$ 
```

**Comment by JamesVanWaza** [comment]
@mrsinguyen Did you do sudo before running compass watch?

**Comment by mrsinguyen** [comment]
Yes, sudo before start compass watch:

```
$ sudo su
Password:
sh-3.2# compass watch
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/vt-theme.no-query.css
    write css/vt-theme.styles.css
NoMethodError on line ["402"] of /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb: undefined method `start' for #<Thread:0x007fd8928377d8 sleep>
Run with --trace to see the full backtrace
sh-3.2# 
```

Full track:

```
sh-3.2# compass watch --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
    write css/vt-theme.no-query.css
    write css/vt-theme.styles.css
NoMethodError on line ["402"] of /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb: undefined method `start' for #<Thread:0x007feaa08377e0 sleep>
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:402:in `map'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:402:in `listen_to'
  /Library/Ruby/Gems/2.0.0/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:338:in `watch'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:44:in `call'
  /Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
  /usr/bin/compass:23:in `load'
  /usr/bin/compass:23:in `<main>'
sh-3.2# 
```

**Comment by mrsinguyen** [comment]
But compass compile work well.

```
$ compass compile
    write css/vt-theme.no-query.css
    write css/vt-theme.styles.css
```

**Comment by JamesVanWaza** [comment]
Ok, no idea on how to fix the error, on that one, but for now if compass compile is working, well and good.

**Comment by cssgdhd** [comment]
I also got a similart error `Errno::EACCES on line ["245"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /css` while I was using `gulp.start('task')` to compile my `sass` file on the node.js serverside.But when I run `gulp` from the terminal,it works well.Could someone help me to solve the problem?
