### ISSUE TITLE
Compass installation fails from base debian:jessie Dockerfile

### ISSUE THREAD

**Issue by ghost** [Compass/compass#2017]
Hello there, 

I am setting up a very basic Dockerfile for installing compass, and it fails with the following issue:

```
ERROR:  Error installing compass:
    ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 -r ./siteconf20150921-13-uce2d1.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/bin/ruby2.1
    --with-ffi_c-dir
    --without-ffi_c-dir
    --with-ffi_c-include
    --without-ffi_c-include=${ffi_c-dir}/include
    --with-ffi_c-lib
    --without-ffi_c-lib=${ffi_c-dir}/lib
    --with-libffi-config
    --without-libffi-config
    --with-pkg-config
    --without-pkg-config
/usr/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
    from /usr/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
    from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from /usr/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
    from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/ffi-1.9.10 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/ffi-1.9.10/gem_make.out
```

Dockerfile:

```
FROM debian:jessie

# Install system packages
RUN \
    apt-get update && apt-get install -y \
        ruby-dev \
        ruby \
        make && \
    rm -rf /var/lib/apt/lists/*

# Install Ruby-based tools
RUN \
    gem update --system && gem install \
        compass \
        compass-rgbapng

```

I have tried a couple things like installing `libffi-dev` with no avail.

**Comment by mprins** [comment]
this really is a ffi problem; ie gem install ffi will fail with the same error.

When you look in the mkmf.log file it will tel you what's missing, probably the ruby native headers...
 alternatively you could use jruby

**Comment by wiibaa** [comment]
I hit the same issue directly on debian:jessie as OS not inside docker.
Installing ruby-ffi package solved it for me

@mprins maybe adding `apt-get install ruby-ffi` to your docker file would solve it for you too

**Comment by ghost** [comment]
@wlibaa thank you! fixed my issue
