### ISSUE TITLE
Error on OS X 10.13, High Sierra.

### ISSUE THREAD

**Issue by MasaruKitajima** [Compass/compass#2127]
I'm using Dreamweaver and setup configuration.
It worked fine until I updated to OS X 10.13. After the update, compiling saas returns error below.
```
Users/MyAccount/Desktop/test/sass/mtnCommon.scss
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'compass' (>= 0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/MyAccount/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /Applications/Koala.app/Contents/Resources/app.nw/bin/compass:17:in `
'
```
`ruby -v` returns ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15] .
`compass -v` returns
```
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2017 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
```
`gem env` returns
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.13
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/thirstytraveler/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/thirstytraveler/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/thirstytraveler/.rbenv/versions/2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/thirstytraveler/.rbenv/versions/2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/thirstytraveler/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/thirstytraveler/.rbenv/versions/2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/thirstytraveler/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0
     - /Users/thirstytraveler/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/thirstytraveler/.rbenv/versions/2.3.1/bin
     - /usr/local/Cellar/rbenv/1.0.0/libexec
     - /Users/thirstytraveler/.rbenv/plugins/ruby-build/bin
     - /Users/thirstytraveler/.rbenv/shims
     - /usr/local/bin
     - /Users/thirstytraveler/cgi-bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /opt/X11/bin
     - /Applications/TeXLive/Library/texlive/2013/bin/x86_64-darwin
     - /Applications/TeXLive/Library/mactexaddons/bin
     - /Applications/eclipse/android/platform-tools
```

I have no idea at all as it's shame, but I'm not good at gems and ruby.

**Comment by niharikag09** [comment]
Hi,

We have fixed this issue from the Dw side, where the script that triggers the compilation was having an issue. 

The fix will be available in the next Dw release.

Regards,
Niharika Gupta
Adobe Dreamweaver

**Comment by MasaruKitajima** [comment]
Thanks!
I'm waiting for new DW coming soon.
