### ISSUE TITLE
Syntax error: Not a valid color stop: blue 33%

### ISSUE THREAD

**Issue by flobby** [Compass/compass#217]
Hi there,

just updated sass / integrated it as independent gem. Now +linear-gradient doesn't work as it has to: It doesn't work anymore with % statements.

To verify, we've tried your documentation example. The Result:

Syntax error: Not a valid color stop: blue 33%
       on line 63 of .../app/stylesheets/appstore.sass, in `linear-gradient'
       from line 63 of .../app/stylesheets/appstore.sass

```
#topbar
  // +linear-gradient(color-stops(#f7931e, #f7931e 50%, #fca136 50%, #fca136))
  +linear-gradient(color-stops(white, blue 33%, black 67%))
  color: cccccc
  height: 66px
```

Versions:

/gems/ree-1.8.7-2010.01/gems/sass-3.1.0.alpha.28
/gems/ree-1.8.7-2010.01/gems/compass-0.10.6

Would love to use +linear-gradient in our app :)

Thank you + greetings from munich.
flo

**Comment by chriseppstein** [comment]
Compass does not yet support sass 3.1 alphas.

**Comment by chriseppstein** [comment]
Use haml 3.0.x and it'll work.

**Comment by flobby** [comment]
thank you!

**Comment by darthschmoo** [comment]
Should this be a closed issue?  It doesn't seem to be working in the latest version of compass either.

Is there a fix in the works?

Thanks!

**Comment by chriseppstein** [comment]
@darthschmoo please provide a reproducible test case.

**Comment by chriseppstein** [comment]
When I run the above example I get:

```
WARNING: The linear-gradient mixin is deprecated. Instead use: @include background-image(linear-gradient(#ffffff, #0000ff 33%, #000000 67%))
        on line 49 of /Users/chris/Work/caring/sites/caring.com/vendor/bundle/ruby/1.9.1/gems/compass-0.11.caring.1.4461f1b/frameworks/compass/stylesheets/compass/css3/_gradient.scss, in `linear-gradient'
        from line 4 of an unknown file

#topbar {
  background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(0%, #ffffff), color-stop(33%, #0000ff), color-stop(67%, #000000));
  background-image: -webkit-linear-gradient(top, #ffffff, #0000ff 33%, #000000 67%);
  background-image: -moz-linear-gradient(top, #ffffff, #0000ff 33%, #000000 67%);
  background-image: -o-linear-gradient(top, #ffffff, #0000ff 33%, #000000 67%);
  background-image: -ms-linear-gradient(top, #ffffff, #0000ff 33%, #000000 67%);
  background-image: linear-gradient(top, #ffffff, #0000ff 33%, #000000 67%);
  color: cccccc;
  height: 66px; }
```

**Comment by darthschmoo** [comment]
Sorry.  I should have read this more carefully.  I think I got distracted by the use of the word 'alphas' in it, because my problem seemed to only crop up with rgba() colors.  I'll file a bug report if it makes sense to do so.

**Comment by chriseppstein** [comment]
@darthschmoo file a bug if you think you found one.

**Comment by krainboltgreene** [comment]
Similar issue:

```
sass (3.1.7)
compass (0.11.5)
```

And the error:

```
/*
Syntax error: Not a valid color stop: Sass::Script::String: color-stop(white, 0.25)
        on line 260 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss, in `gradient-vertical-three-colors'
        from line 187 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss, in `button'
        from line 110 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_scaffolding.scss
        from line 24 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/application.scss

Backtrace:
/Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss:260:in `gradient-vertical-three-colors'
/Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss:187:in `button'
/Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_scaffolding.scss:110
/Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/application.scss:24
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/compass-0.11.5/lib/compass/sass_extensions/functions/gradient_support.rb:238:in `block in color_stops'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/compass-0.11.5/lib/compass/sass_extensions/functions/gradient_support.rb:229:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/compass-0.11.5/lib/compass/sass_extensions/functions/gradient_support.rb:229:in `color_stops'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/compass-0.11.5/lib/compass/sass_extensions/functions/gradient_support.rb:285:in `linear_gradient'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/script/funcall.rb:88:in `_perform'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/script/node.rb:40:in `perform'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:215:in `visit_prop'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `block (2 levels) in visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `block in visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `block (2 levels) in visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `block in visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:200:in `visit_mixin'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:235:in `visit_rule'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:145:in `block in visit_import'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:145:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:145:in `visit_import'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:18:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/tree/root_node.rb:20:in `render'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/engine.rb:293:in `_render'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/engine.rb:241:in `block in render'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/util.rb:297:in `silence_sass_warnings'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/engine.rb:241:in `render'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:319:in `update_stylesheet'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:181:in `block (2 levels) in update_stylesheets'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:175:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:175:in `block in update_stylesheets'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:173:in `each'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/compiler.rb:173:in `update_stylesheets'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin.rb:81:in `update_stylesheets'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin.rb:54:in `check_for_updates'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/sass-3.1.7/lib/sass/plugin/rack.rb:51:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/head.rb:14:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/rack-1.2.3/lib/rack/methodoverride.rb:24:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/flash.rb:182:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/cookies.rb:302:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activerecord-3.0.10/lib/active_record/query_cache.rb:32:in `block in call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activerecord-3.0.10/lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activerecord-3.0.10/lib/active_record/query_cache.rb:12:in `cache'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activerecord-3.0.10/lib/active_record/query_cache.rb:31:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activerecord-3.0.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/activesupport-3.0.10/lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/callbacks.rb:44:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/rack-1.2.3/lib/rack/sendfile.rb:107:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/railties-3.0.10/lib/rails/rack/logger.rb:13:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/rack-1.2.3/lib/rack/runtime.rb:17:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/rack-1.2.3/lib/rack/lock.rb:11:in `block in call'
<internal:prelude>:10:in `synchronize'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/rack-1.2.3/lib/rack/lock.rb:11:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/actionpack-3.0.10/lib/action_dispatch/middleware/static.rb:30:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/hoptoad_notifier-2.4.11/lib/hoptoad_notifier/user_informer.rb:12:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/railties-3.0.10/lib/rails/application.rb:168:in `call'
/Users/krainboltgreene/.rvm/gems/ruby-1.9.2-p290@rubygems.org/gems/railties-3.0.10/lib/rails/application.rb:77:in `method_missing'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:146:in `handle'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:99:in `rescue in block (2 levels) in start'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:96:in `block (2 levels) in start'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:86:in `each'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:86:in `block in start'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:66:in `loop'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:66:in `start'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/lib/nack/server.rb:13:in `run'
/Users/krainboltgreene/Library/Application Support/Pow/Versions/0.3.2/node_modules/nack/bin/nack_worker:4:in `<main>'
*/
body:before {
  white-space: pre;
  font-family: monospace;
  content: "Syntax error: Not a valid color stop: Sass::Script::String: color-stop(white, 0.25)\A         on line 260 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss, in `gradient-vertical-three-colors'\A         from line 187 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_preboot.scss, in `button'\A         from line 110 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/_scaffolding.scss\A         from line 24 of /Users/krainboltgreene/repo/ruby/rails/rubygems.org/app/assets/stylesheets/application.scss"; }
```

Works just fine in a project that doesn't use Compass.

**Comment by Taiger** [comment]
This still appears to be an issue.

On a sidenote, is there a way to turn off linting?

Test Case:

``` sass
@mixin bgRad($startStop:'at center center',$firstColor:'#E1F0F5 0%',$secondColor:'#FFFFFF 100%') {
background: radial-gradient($startStop, $firstColor, $secondColor);
}

.myselector {
@include bgRad();
}
```

Result:

```
error sass/style.scss (Line 36 of sass/partials/global/_mixins.scss: Not a valid color stop: Sass::Script::String: "#FFFFFF 100%")
```

Expected:

``` css
background-image: radial-gradient(at top center , #E1F0F5 0%, #FFFFFF 100%);
```

Thanks!

**Comment by cimmanon** [comment]
Your arguments should not be strings:

``` scss
@mixin bgRad($startStop:at center center,$firstColor:#E1F0F5 0%,$secondColor:#FFFFFF 100%) {
    background: radial-gradient($startStop, $firstColor, $secondColor);
}
```
