### ISSUE TITLE
Compass doesn't work in some environments

### ISSUE THREAD

**Issue by sporkmonger** [Compass/compass#23]
I've tried running it in Ruby 1.9 and Ruby 1.8.7 p72 and both failed.  The copy of Ruby that comes with OS X Leopard seems to like it just fine.

```
>> require "compass"
NameError: uninitialized constant Sass::Script
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass/sass_extensions/functions.rb:8:in `<top (required)>'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass/sass_extensions.rb:4:in `require'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass/sass_extensions.rb:4:in `<top (required)>'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass.rb:5:in `require'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass.rb:5:in `block in <top (required)>'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass.rb:4:in `each'
  from /usr/local/ruby19/lib/ruby/gems/1.9.1/gems/chriseppstein-compass-0.8.1/lib/compass.rb:4:in `<top (required)>'
  from (irb):3:in `require'
  from (irb):3
  from /usr/local/bin/irb19:12:in `<main>'
```

**Comment by chriseppstein** [comment]
What version of haml do you have installed? This is likely because you have haml 2.0 and not 2.2 or haml-edge.

**Comment by sporkmonger** [comment]
Yeah, I figured that out, but forgot to close this issue.
