### ISSUE TITLE
Error after upgrade to v.0.11

### ISSUE THREAD

**Issue by lmartins** [Compass/compass#251]
After upgrading to the latest version, i get the following error when i try to run any command in compass:

/Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass/sass_extensions/monkey_patches/browser_support.rb:68: undefined method `to_literal' for class`Sass::Script::Funcall' (NameError)
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass/sass_extensions/monkey_patches.rb:2
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass/sass_extensions/monkey_patches.rb:1
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass/sass_extensions.rb:5
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass.rb:5
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass.rb:4:in`each'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/lib/compass.rb:4
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
    from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:29:in`require'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/bin/compass:20
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/bin/compass:8:in `fallback_load_path'
    from /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.0/bin/compass:19
    from /usr/bin/compass:19:in`load'
    from /usr/bin/compass:19

**Comment by lmartins** [comment]
Sorry, not a bug. Had to force update to SASS in order to get it to work.
