### ISSUE TITLE
Stack level too deep when using 30+ images in sprite

### ISSUE THREAD

**Issue by roytomeij** [Compass/compass#274]
In one particular project (running in Middleman) a "stack level too deep" error occurs when using over 30 images in a sprite directory. Is this a known error? Stack trace below.

```
SystemStackError: stack level too deep
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:177:in `encode_png_image_pass_to_stream'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:177:in `encode_png_image_without_interlacing'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:164:in `encode_png_pixelstream'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:83:in `to_datastream'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/image.rb:62:in `to_datastream'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:34:in `write'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:41:in `save'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:41:in `open'
    /Library/Ruby/Gems/1.8/gems/chunky_png-0.12.0/lib/chunky_png/canvas/png_encoding.rb:41:in `save'
    /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:183:in `save!'
    /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:126:in `generate'
    /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:294:in `sprite_url'
    /Library/Ruby/Gems/1.8/gems/compass-0.11.beta.2/lib/compass/sass_extensions/functions/sprites.rb:258:in `sprite'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/funcall.rb:89:in `send'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/funcall.rb:89:in `_perform'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/node.rb:67:in `perform'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/list.rb:61:in `_perform'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/list.rb:61:in `map'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/list.rb:61:in `_perform'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/script/node.rb:67:in `perform'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:212:in `visit_prop'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:232:in `visit_rule'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:27:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:39:in `with_environment'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:26:in `visit_children'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:47:in `visit_root'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:18:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:7:in `send'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/visitors/perform.rb:7:in `visit'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/tree/root_node.rb:20:in `render'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/engine.rb:302:in `_render'
    /Library/Ruby/Gems/1.8/gems/sass-3.1.0.alpha.221/lib/sass/../sass/engine.rb:249:in `render_without_lemonade'
    /Library/Ruby/Gems/1.8/gems/lemonade-0.3.4/lib/lemonade.rb:58:in `render'
    /Library/Ruby/Gems/1.8/gems/tilt-1.1/lib/tilt.rb:552:in `evaluate'
    /Library/Ruby/Gems/1.8/gems/tilt-1.1/lib/tilt.rb:128:in `render'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:452:in `render'
    /Library/Ruby/Gems/1.8/gems/padrino-core-0.9.19/lib/padrino-core/application/rendering.rb:123:in `render'
    /Users/roy/src/middleman/bin/../lib/middleman/server.rb:122:in `process_request'
    /Users/roy/src/middleman/bin/../lib/middleman/server.rb:109
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:783:in `instance_eval'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:783:in `error_block!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:778:in `each'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:778:in `error_block!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:531:in `call!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `instance_eval'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `invoke'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `catch'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:706:in `invoke'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:531:in `call!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:516:in `call'
    /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/conditionalget.rb:25:in `call'
    /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/showexceptions.rb:24:in `call'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:1142:in `call'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:1168:in `synchronize'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.1.0/lib/sinatra/base.rb:1142:in `call'
    /Library/Ruby/Gems/1.8/gems/shotgun-0.8/lib/shotgun/loader.rb:86:in `proceed_as_child'
    /Library/Ruby/Gems/1.8/gems/shotgun-0.8/lib/shotgun/loader.rb:31:in `call!'
    /Library/Ruby/Gems/1.8/gems/shotgun-0.8/lib/shotgun/loader.rb:18:in `call'
    /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
    /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/chunked.rb:15:in `call'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'
    /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    /Library/Ruby/Gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'
    /Library/Ruby/Gems/1.8/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'
    /Library/Ruby/Gems/1.8/gems/rack-1.2.1/lib/rack/handler/thin.rb:14:in `run'
    /Users/roy/src/middleman/bin/mm-server:65
```

**Comment by chriseppstein** [comment]
I've personally made sprite maps with more than 30 images in them. Are you sure this is about how many images and not due to a strange image?

**Comment by chriseppstein** [comment]
You can try generating a sprite file with the `--skip-overrides` option instead of using the autogenerated one.

**Comment by roytomeij** [comment]
I also have projects with well over 30 images. In this particular project I tried different files as the 31st one. Let me see if they aren't all corrupt in some way.

**Comment by chriseppstein** [comment]
Any followup?

**Comment by chriseppstein** [comment]
Closing. There's not much I can do about this from compass, I filed a sass bug for it: https://github.com/nex3/sass/issues/issue/48

**Comment by chriseppstein** [comment]
I made a sprite with 200+images the other day and it worked fine in ruby 1.9.2.
