### ISSUE TITLE
How to setup offline documentation?

### ISSUE THREAD

**Issue by millisami** [Compass/compass#328]
Hi, I followed this instruction at https://github.com/chriseppstein/compass/tree/stable/doc-src README and fired up the server.

```
➜ (ruby-1.9.2-p180) doc-src git:(stable) ✗ bundle exec nanoc3 aco -p 4000
Running on http://0.0.0.0:4000/
[2011-04-05 17:02:49] INFO  WEBrick 1.3.1
[2011-04-05 17:02:49] INFO  ruby 1.9.2 (2011-02-18) [x86_64-darwin10.6.0]
[2011-04-05 17:02:49] INFO  WEBrick::HTTPServer#start: pid=20844 port=4000
```

Then when I visit `localhost:4000/docs`, I just get `File not found: /docs` in the browser.
Is this the right way to setup the offline documentation?
Or is there any other instruction on how to setup offline documentation?

**Comment by chriseppstein** [comment]
the nanoc aco approach is for developing the docs. best to just compile them once with `bundle exec nanoc3 co` and then run `bundle exec serve ..`. Lastly, make sure to add a trailing slash to your URL: `http://localhost:4000/docs/`

Let me know if that doesn't work for you.

**Comment by millisami** [comment]
Thanks, that solved the previous error. But now after successful compilation of the docs, some syntax error shows up.

```
➜ (ruby-1.9.2-p180) doc-src git:(stable) ✗ pwd
/Users/millisami/documentations/compass/doc-src
➜ (ruby-1.9.2-p180) doc-src git:(stable) ✗ be nanoc3 co                                                                              
Loading site data...
Compiling site...
      create  [0.21s]  ../docs/CHANGELOG-v0-10-0-beta/index.html
      create  [0.02s]  ../docs/CHANGELOG/index.html
      create  [0.01s]  ../docs/copyright/index.html
      create  [0.22s]  ../docs/examples/blueprint/grid/pull/index.html
      create  [0.38s]  ../docs/examples/blueprint/grid/two_cols/index.html
      create  [0.43s]  ../docs/examples/compass/css3/background-clip/index.html
      create  [0.12s]  ../docs/examples/compass/css3/background-origin/index.html
      create  [0.12s]  ../docs/examples/compass/css3/background-size/index.html
      create  [0.36s]  ../docs/examples/compass/css3/border_radius/index.html
      create  [0.11s]  ../docs/examples/compass/css3/box/index.html
      create  [0.11s]  ../docs/examples/compass/css3/box_shadow/index.html
      create  [0.11s]  ../docs/examples/compass/css3/box_sizing/index.html
      create  [0.11s]  ../docs/examples/compass/css3/columns/index.html
      create  [0.08s]  ../docs/examples/compass/css3/font-face/index.html
      create  [0.14s]  ../docs/examples/compass/css3/gradient/index.html
      create  [0.10s]  ../docs/examples/compass/css3/inline_block/index.html
      create  [0.11s]  ../docs/examples/compass/css3/opacity/index.html
      create  [0.11s]  ../docs/examples/compass/css3/text_shadow/index.html
      create  [0.12s]  ../docs/examples/compass/css3/transform/index.html
      create  [0.12s]  ../docs/examples/compass/css3/transition/index.html
      create  [0.04s]  ../docs/examples/compass/helpers/elements-of-type/index.html
      create  [0.03s]  ../docs/examples/compass/helpers/enumerate/index.html
      create  [0.04s]  ../docs/examples/compass/helpers/using-extend-in-place-of-enumerate/index.html
      create  [0.06s]  ../docs/examples/compass/layout/sticky-footer/index.html
      create  [0.09s]  ../docs/examples/compass/tables/all/index.html
      create  [0.04s]  ../docs/examples/compass/tables/borders/index.html
      create  [0.03s]  ../docs/examples/compass/tables/scaffolding/index.html
      create  [0.04s]  ../docs/examples/compass/tables/striping/index.html
      create  [0.02s]  ../docs/frameworks/index.html
      create  [1.06s]  ../docs/index/mixins/index.html
      create  [0.02s]  ../docs/index/variables/index.html
      create  [0.02s]  ../docs/index.html
      create  [0.07s]  ../docs/reference/blueprint/buttons/index.html
      create  [0.10s]  ../docs/reference/blueprint/colors/index.html
      create  [0.06s]  ../docs/reference/blueprint/debug/index.html
      create  [0.06s]  ../docs/reference/blueprint/fancy_type/index.html
      create  [0.10s]  ../docs/reference/blueprint/form/index.html
      create  [0.08s]  ../docs/reference/blueprint/grid/index.html
      create  [0.06s]  ../docs/reference/blueprint/ie/index.html
      create  [0.10s]  ../docs/reference/blueprint/interaction/index.html
      create  [0.06s]  ../docs/reference/blueprint/link_icons/index.html
      create  [0.11s]  ../docs/reference/blueprint/liquid/index.html
      create  [0.06s]  ../docs/reference/blueprint/print/index.html
      create  [0.07s]  ../docs/reference/blueprint/reset/utilities/index.html
      create  [0.10s]  ../docs/reference/blueprint/reset/index.html
      create  [0.07s]  ../docs/reference/blueprint/rtl/index.html
      create  [0.06s]  ../docs/reference/blueprint/scaffolding/index.html
      create  [0.11s]  ../docs/reference/blueprint/typography/index.html
      create  [0.06s]  ../docs/reference/blueprint/utilities/index.html
      create  [0.11s]  ../docs/reference/blueprint/index.html
      create  [0.12s]  ../docs/reference/compass/css3/background_clip/index.html
      create  [0.19s]  ../docs/reference/compass/css3/background_origin/index.html
      create  [0.10s]  ../docs/reference/compass/css3/background_size/index.html
      create  [0.14s]  ../docs/reference/compass/css3/border_radius/index.html
      create  [0.10s]  ../docs/reference/compass/css3/box/index.html
      create  [0.13s]  ../docs/reference/compass/css3/box_shadow/index.html
      create  [0.13s]  ../docs/reference/compass/css3/box_sizing/index.html
      create  [0.09s]  ../docs/reference/compass/css3/columns/index.html
      create  [0.13s]  ../docs/reference/compass/css3/font_face/index.html
      create  [0.10s]  ../docs/reference/compass/css3/gradient/index.html
      create  [0.13s]  ../docs/reference/compass/css3/inline_block/index.html
      create  [0.10s]  ../docs/reference/compass/css3/opacity/index.html
      create  [0.14s]  ../docs/reference/compass/css3/shared/index.html
      create  [0.13s]  ../docs/reference/compass/css3/text_shadow/index.html
      create  [0.10s]  ../docs/reference/compass/css3/transform/index.html
      create  [0.13s]  ../docs/reference/compass/css3/transition/index.html
      create  [0.12s]  ../docs/reference/compass/css3/index.html
      create  [0.13s]  ../docs/reference/compass/helpers/color-stops/index.html
      create  [0.08s]  ../docs/reference/compass/helpers/constants/index.html
      create  [0.12s]  ../docs/reference/compass/helpers/display/index.html
      create  [0.08s]  ../docs/reference/compass/helpers/font-files/index.html
      create  [0.12s]  ../docs/reference/compass/helpers/image-dimensions/index.html
      create  [0.08s]  ../docs/reference/compass/helpers/inline-data/index.html
      create  [0.13s]  ../docs/reference/compass/helpers/selectors/index.html
      create  [0.09s]  ../docs/reference/compass/helpers/urls/index.html
      create  [0.12s]  ../docs/reference/compass/helpers/index.html
      create  [0.09s]  ../docs/reference/compass/layout/sticky_footer/index.html
      create  [0.14s]  ../docs/reference/compass/layout/index.html
      create  [0.13s]  ../docs/reference/compass/reset/utilities/index.html
      create  [0.09s]  ../docs/reference/compass/reset/index.html
      create  [0.13s]  ../docs/reference/compass/support/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/general/clearfix/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/general/float/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/general/hacks/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/general/min/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/general/reset/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/general/tag_cloud/index.html
      create  [0.13s]  ../docs/reference/compass/utilities/general/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/links/hover_link/index.html
      create  [0.11s]  ../docs/reference/compass/utilities/links/link_colors/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/links/unstyled_link/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/links/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/lists/bullets/index.html
      create  [0.13s]  ../docs/reference/compass/utilities/lists/horizontal_list/index.html
      create  [0.09s]  ../docs/reference/compass/utilities/lists/inline-block-list/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/lists/inline_list/index.html
      create  [0.09s]  ../docs/reference/compass/utilities/lists/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/print/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/sprites/sprite_img/index.html
      create  [0.15s]  ../docs/reference/compass/utilities/sprites/index.html
      create  [0.10s]  ../docs/reference/compass/utilities/tables/alternating_rows_and_columns/index.html
      create  [0.17s]  ../docs/reference/compass/utilities/tables/borders/index.html
      create  [0.13s]  ../docs/reference/compass/utilities/tables/scaffolding/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/tables/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/text/ellipsis/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/text/nowrap/index.html
      create  [0.12s]  ../docs/reference/compass/utilities/text/replacement/index.html
      create  [0.08s]  ../docs/reference/compass/utilities/text/index.html
      create  [0.13s]  ../docs/reference/compass/utilities/index.html
      create  [0.13s]  ../docs/reference/compass/index.html
      create  [0.01s]  ../docs/screencast/index.html
      create  [0.01s]  ../docs/search/index.html
      create  [0.27s]  ../docs/stylesheets/ie.css
      create  [0.10s]  ../docs/stylesheets/print.css
      create  [0.68s]  ../docs/stylesheets/screen.css
      create  [0.03s]  ../docs/tutorials/best_practices/index.html
      create  [0.07s]  ../docs/tutorials/blueprint/index.html
      create  [0.03s]  ../docs/tutorials/command-line/index.html
      create  [0.04s]  ../docs/tutorials/configurable-variables/index.html
      create  [0.03s]  ../docs/tutorials/configuration-reference/index.html
      create  [0.03s]  ../docs/tutorials/contributing/index.html
      create  [0.08s]  ../docs/tutorials/extensions/index.html
      create  [0.03s]  ../docs/tutorials/production-css/index.html
      create  [0.03s]  ../docs/tutorials/index.html
      create  [0.00s]  ../docs/fonts/examples/bgrove.otf
      create  [0.00s]  ../docs/fonts/examples/bgrove.ttf
      create  [0.00s]  ../docs/images/compass.png
      create  [0.00s]  ../docs/images/compass_icon.png
      create  [0.00s]  ../docs/images/examples/css3/bg-origin/bg.png
      create  [0.00s]  ../docs/javascripts/fixups.js
      create  [0.00s]  ../docs/javascripts/jquery-1.3.2.min.js
      create  [0.00s]  ../docs/javascripts/jquery.url.packed.js
      create  [0.29s]  ../docs/javascripts/search-data.js

Site compiled in 14.79s.
➜ (ruby-1.9.2-p180) doc-src git:(stable) ✗ be serve
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/view_helpers.rb:100: warning: else without rescue is useless
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require': /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/view_helpers.rb:97: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
        when 'true', '1'  : true
                           ^
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/view_helpers.rb:98: syntax error, unexpected ',', expecting keyword_end
        when 'false', '0' :  false
                     ^
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/view_helpers.rb:98: syntax error, unexpected ':', expecting keyword_end
        when 'false', '0' :  false
                           ^
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/view_helpers.rb:276: syntax error, unexpected keyword_end, expecting $end
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve/handlers/dynamic_handler.rb:1:in `<top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/lib/serve.rb:6:in `<top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `block in require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:156:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/serve-0.10.2/bin/serve:13:in `<top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/bin/serve:19:in `load'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/bin/serve:19:in `<main>'
```

**Comment by chriseppstein** [comment]
hmmm. looks like ruby does not like something in serve. I don't get this error locally when I use 1.9.2-p180 and compass/master. Very strange.
