### ISSUE TITLE
Encoding error on compass font-face mixin

### ISSUE THREAD

**Issue by morgoth** [Compass/compass#377]
I'm getting error similar to: https://github.com/chriseppstein/compass/issues/196

My stacktrace:

```
Sass::SyntaxError - Invalid US-ASCII character "\xE2":
/app/.bundle/gems/ruby/1.9.1/gems/compass-0.11.1/frameworks/compass/stylesheets/compass/css3/_font-face.scss:40
/app/.bundle/gems/ruby/1.9.1/gems/compass-0.11.1/frameworks/compass/stylesheets/compass/_css3.scss:14
/app/views/stylesheets/screen.sass:11
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:350:in `block in check_encoding!'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:440:in `rescue in block in check_encoding'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:437:in `block in check_encoding'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:436:in `each'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:436:in `each_with_index'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:436:in `check_encoding'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/util.rb:489:in `check_sass_encoding'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:349:in `check_encoding!'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:316:in `_to_tree'
/app/.bundle/gems/ruby/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:250:in `to_tree'
```

You can find source of this app on: https://github.com/morgoth/bridge-score
Not really sure if this is compass or sass problem.

**Comment by rstacruz** [comment]
Same, using compass 0.11.1 and haml-3.0.18 here.

**Comment by software-project** [comment]
Same for compass 0.11.1 and 3.2.0.alpha.3

**Comment by dblock** [comment]
I think the problem is the default character encoding. See https://github.com/nex3/haml/issues/269.

**Comment by wprater** [comment]
Im getting this same issue while using Ruby 1.9, rvm, and pow.

**Comment by rstacruz** [comment]
Fixed it by adding this to my app's initializers:

``` ruby
Encoding.default_encoding = 'utf-8'
```

**Comment by morgoth** [comment]
@rstacruz you mean: `Encoding.default_external`
Yes, this fixes problem.

**Comment by wprater** [comment]
The issue must be with rvm then, since the Encoding get reset out of my environment.

**Comment by markushausammann** [comment]
Had a similar problem and solved it by adding @charset "UTF-8"; to my font partial.
