### ISSUE TITLE
Functions that log warnings only work when compiling with the command line tool

### ISSUE THREAD

**Issue by mocoso** [Compass/compass#382]
Functions that log warnings only work when using the command line tool, for example if you use

```
@include background(radial-gradient(center 150%, #777788, #000000 500px));
```

in your scss file and run compile with

```
compass compile
```

Your file compiles correctly and the warning "PIE does not support radial-gradient." is logged to the console.

However if you use this same line in scss file in a rails app and let the rails app compile the templates when required then you get the error

```
NameError: uninitialized constant Compass::Logger
```

This is because the Compass::Logger class is only required in exec.rb which is loaded by the command line tool but not when compass is used from within a rails app.

**Comment by ivanovv** [comment]
Same problem here:

```
bundle exec rake ts:rebuild --trace
(in /home/vic/ruby/pricer)
** Invoke ts:rebuild (first_time)
** Invoke thinking_sphinx:rebuild (first_time)
** Invoke thinking_sphinx:app_env (first_time)
** Execute thinking_sphinx:app_env
rake aborted!
uninitialized constant Compass::Logger
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/version.rb:56:in `const_missing'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/actions.rb:7:in `logger'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/actions.rb:106:in `log_action'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/actions.rb:73:in `remove'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/compiler.rb:80:in `block in clean!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/compiler.rb:79:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/compiler.rb:79:in `clean!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/configuration/helpers.rb:141:in `handle_configuration_change!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/app_integration/rails.rb:61:in `initialize!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/compass-0.11.3/lib/compass/app_integration/rails/actionpack3/railtie.rb:43:in `block in <class:Railtie>'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `run'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `block in run_initializers'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/application.rb:134:in `initialize!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
/home/vic/ruby/pricer/config/environment.rb:5:in `<top (required)>'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/railties-3.0.7/lib/rails/application.rb:103:in `require_environment!'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/thinking-sphinx-2.0.5/lib/thinking_sphinx/tasks.rb:7:in `block (2 levels) in <top (required)>'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/home/vic/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
/home/vic/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
/home/vic/.rvm/rubies/ruby-1.9.2-p136/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/vic/.rvm/gems/ruby-1.9.2-p136/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/home/vic/.rvm/gems/ruby-1.9.2-p136/bin/rake:19:in `load'
/home/vic/.rvm/gems/ruby-1.9.2-p136/bin/rake:19:in `<main>'
```

**Comment by ivanovv** [comment]
fixed for me by running compass clean && compass compile

**Comment by chriseppstein** [comment]
I have added a logger in sass 3.1.3. I will update the compass logger to log to this and then when sass is in some environment with a special logger it will all just work. Specifically, the sass-rails gem will provide logging integration between sass and rails.

**Comment by ivanovv** [comment]
Sounds great!
