### ISSUE TITLE
Cannot use sprite with sass --compass

### ISSUE THREAD

**Issue by MoOx** [Compass/compass#395]
I'm trying to use sprite mixins  but I'm using sass --compass (since
I'm waiting for compass to have an import path command line option)
When I use sass --compass for a code which work with normal compass bin, i've this error:
NoMethodError: undefined method `top' for nil:NilClass

Chris tell me it's is normal. So here is the stacktrace:

```
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/sass_extensions/
sprites/base.rb:54:in `compute_image_metadata!': undefined method
`top' for nil:NilClass (NoMethodError)
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:39:in `initialize'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:15:in `new'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:15:in `from_uri'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/functions/sprites.rb:24:in `sprite_map'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/funcall.rb:80:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/funcall.rb:80:in `_perform'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/node.rb:40:in `perform'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:236:in `visit_variable'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:18:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `map'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:27:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:39:in `with_environment'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:26:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:47:in `visit_root'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:18:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:7:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:7:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/root_node.rb:20:in `render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
engine.rb:291:in `_render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
engine.rb:238:in `render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:316:in `process_result'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:41:in `parse'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:21:in `parse!'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/sass:8
       from /usr/bin/sass:19:in `load'
       from /usr/bin/sass:19
```

**Comment by philippbosch** [comment]
@jezdez is currently trying to add Compass support to django-compressor (jezdez/django_compressor@d0411eba021c54e4f0f56ff8a54319fa7ebf398a). It's also relying on `sass --compass` which works fine so far except that we also experience the same issue described here when trying to use sprites. Any hint much appreciated.

**Comment by MoOx** [comment]
It's not a bug from compass, just a bad usage.
It's a configuration problem.
See https://github.com/nex3/sass/issues/89

For the PHP filter I've rewritten, I do not use sass --compass anymore. See https://github.com/MoOx/assetic/blob/compass-bin/src/Assetic/Filter/CompassFilter.php
