### ISSUE TITLE
ENOENT crash watching files over sshfs mount

### ISSUE THREAD

**Issue by jessor** [Compass/compass#426]
Not sure if I'm right here or if I should post this with fssm. Apologies if I'm wrong.

The following error happens reproducably when I watch a folder mounted via sshfs and change sth in a stylesheet.

```
$ mount
...
myuser@remotehost.com:/usr/home/myuser/public_html/2011/wp-content/themes on /home/myuser/code/sshfs type fuse.sshfs (rw,nosuid,nodev,max_read=65536,user=myuser)
...

$ pwd 
~/code/sshfs/myproject-2011.2

$ compass watch --trace           
>>> Change detected to: style.scss
overwrite style.css 
>>> Compass is watching for changes. Press Ctrl-C to Stop.
Errno::ENOENT on line ["822"] of /home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/pathname.rb: No such file or directory - /home/myuser/code/sshfs/myproject-2011.2/sass/style.scss
  /home/myuser/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/pathname.rb:822:in `ftype'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/tree.rb:131:in `from_path'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/tree.rb:68:in `set'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/tree.rb:149:in `set'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:59:in `block in add_glob'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:58:in `each'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:58:in `add_glob'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:54:in `block in snapshot'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:54:in `each'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:54:in `snapshot'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:46:in `recache'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/state/directory.rb:13:in `refresh'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/backends/inotify.rb:12:in `block in add_handler'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:191:in `call'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:191:in `block in watch'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/watcher.rb:41:in `[]'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/watcher.rb:41:in `callback!'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/event.rb:128:in `callback!'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:220:in `block in process'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:220:in `each'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:220:in `process'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/rb-inotify-0.8.5/lib/rb-inotify/notifier.rb:203:in `run'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/backends/inotify.rb:20:in `run'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm/monitor.rb:26:in `run'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/fssm-0.2.7/lib/fssm.rb:20:in `monitor'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/lib/compass/commands/watch_project.rb:86:in `perform'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/lib/compass/commands/base.rb:18:in `execute'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/lib/compass/commands/project_base.rb:19:in `execute'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/bin/compass:25:in `block in <top (required)>'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/bin/compass:39:in `call'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/gems/compass-0.11.2/bin/compass:39:in `<top (required)>'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/bin/compass:19:in `load'
  /home/myuser/.rvm/gems/ruby-1.9.2-p180/bin/compass:19:in `<main>'
```

**Comment by chriseppstein** [comment]
fssm has some issues with slow filesystems. Try adding --poll to the command
options.

**Comment by jessor** [comment]
@chriseppstein yep, this fixes it for me. thanks!
