### ISSUE TITLE
undefined method `sass' in production mode

### ISSUE THREAD

**Issue by masterkain** [Compass/compass#461]
Hello, I'm trying to start my Rails 3.1 app in production mode:

```
gem "rails", git: "git://github.com/rails/rails.git", branch: "3-1-stable"
gem "compass", git: "git://github.com/chriseppstein/compass.git", branch: "rails31"
group :assets do
  gem "sass-rails", git: "git://github.com/rails/sass-rails.git", branch: "3-1-stable"
  gem "coffee-rails", git: "git://github.com/rails/coffee-rails.git", branch: "3-1-stable"
  gem "uglifier", git: "git://github.com/lautis/uglifier.git"
end
```

Results in:

```
undefined method `sass' for #<Rails::Application::Configuration:0x00000104550910>

/Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/railtie/configuration.rb:78:in `method_missing': undefined method `sass' for #<Rails::Application::Configuration:0x00000104550910> (NoMethodError)
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/compass-2124003550bf/lib/compass/configuration/helpers.rb:82:in `block in configure_rails!'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/compass-2124003550bf/lib/compass/configuration/helpers.rb:81:in `each'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/compass-2124003550bf/lib/compass/configuration/helpers.rb:81:in `configure_rails!'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/compass-2124003550bf/lib/compass/app_integration/rails/actionpack31/railtie.rb:47:in `block in <class:Railtie>'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/initializable.rb:25:in `instance_exec'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/initializable.rb:25:in `run'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/initializable.rb:49:in `each'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/initializable.rb:49:in `run_initializers'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/application.rb:92:in `initialize!'
    from /Users/kain/.rvm/gems/ruby-1.9.2-p180/bundler/gems/rails-07ea84a03b2a/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/kain/Sites/myapp/config/environment.rb:5:in `<top (required)>'
```

Anything I can check? I stay up to date with the asset pipeline and updated all my config files accordingly to the latest rails.

**Comment by scottdavis** [comment]
<pre>
undefined method `sass' for #<Rails::Application::Configuration:0x00000104550910>
</pre>


post your application.rb

**Comment by masterkain** [comment]
Here it is: http://pastie.org/private/fqjiqawwbc6e4chbl3mtiq

**Comment by mdeering** [comment]
I ran up against this issue today while upgrading from 3.0 to 3.1

Fix for me was to add the following to my Gemfile

```
gem 'sass'
gem 'sass-rails', '>=3.1.0.rc.4'
```

The missing sass-rails gem was the culprit in my case.

**Comment by huerlisi** [comment]
@masterkain according to this [howto](http://metaskills.net/2011/07/29/use-compass-sass-framework-files-with-the-rails-3.1.0.rc5-asset-pipeline/) you should use the following in your `application.rb`:

```
Bundler.require *Rails.groups(:assets) if defined?(Bundler)
```

This is also what a fresh generated application with rails 3.1.0.rc5 brings up.

**Comment by scottdavis** [comment]
you no longer need the sass gem in rails 3.1 just sass-rails

**Comment by masterkain** [comment]
@huerlisi yeah I'm doing that, old post, keeping up with the changes
