### ISSUE TITLE
Malformed version number string 0.11.3.rails.0 / 0.12.0.alpha.0.b1b6273

### ISSUE THREAD

**Issue by camelpunch** [Compass/compass#490]
I'm getting behaviour similar to https://github.com/chriseppstein/compass/issues/140 with both master and rails31 branches when using bundler with the :git option. This is through Passenger on REE.

Incidentally, when I try 'rails c development' I get the following:

```
/Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-3.1.0.rc4/lib/action_view/helpers/asset_tag_helpers/asset_paths.rb:66: uninitialized constant ActionView::Helpers::AssetTagHelper::AssetPaths::Mutex (NameError)
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-3.1.0.rc4/lib/action_view/helpers/asset_tag_helper.rb:3:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-3.1.0.rc4/lib/action_view/helpers/asset_tag_helper.rb:3
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/actionpack-3.1.0.rc4/lib/action_view/helpers.rb:38
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration/rails/runtime.rb:25
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration/rails.rb:5:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration/rails.rb:5
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration.rb:2:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration.rb:2
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration.rb:1:in `each'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass/app_integration.rb:1
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass.rb:31:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass.rb:31
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass.rb:30:in `each'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/bundler/gems/compass-b1b6273b3fa5/lib/compass.rb:30
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:68:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:68:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:66:in `each'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:66:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:55:in `each'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler/runtime.rb:55:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/bundler-1.0.11/lib/bundler.rb:120:in `require'
    from /Users/andrew/dev/tutors/config/application.rb:7
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/railties-3.1.0.rc4/lib/rails/commands.rb:38:in `require'
    from /Users/andrew/.rvm/gems/ree-1.8.7-2011.03/gems/railties-3.1.0.rc4/lib/rails/commands.rb:38
    from script/rails:6:in `require'
    from script/rails:6
```

**Comment by thedarkone** [comment]
`Malformed version number string 0.12.0.alpha.0.` errors are a result of quite a spartan ENV setup under which Passenger's ruby is started. You probably have `git` installed via MacPorts and its additional path prefix (`/opt/local/bin`) isn't prepended to the $PATH env var.

Compass tries to use current `HEAD`'s hash for its version string, but fails because the `git` binary isn't available: https://github.com/chriseppstein/compass/blob/91a748a916360057b5ca/lib/compass/version.rb#L44.

**Comment by camelpunch** [comment]
Thanks, that sounds about right. Will close in anticipation of this being the fix.
