### ISSUE TITLE
Rails 3.1 rc5 and Compass failing to load

### ISSUE THREAD

**Issue by natebird** [Compass/compass#499]
I am using the Rails31 branch of Compass. Here is backtrace:

```
NoMethodError: undefined method `sass' for #<Rails::Application::Configuration:0x1027c3348>
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/railtie/configuration.rb:78:in `method_missing'
~/.rvm/gems/ree-1.8.7-2011.03@app/bundler/gems/compass-91a748a91636/lib/compass/configuration/helpers.rb:82:in `configure_rails!'
~/.rvm/gems/ree-1.8.7-2011.03@app/bundler/gems/compass-91a748a91636/lib/compass/configuration/helpers.rb:81:in `each'
~/.rvm/gems/ree-1.8.7-2011.03@app/bundler/gems/compass-91a748a91636/lib/compass/configuration/helpers.rb:81:in `configure_rails!'
~/.rvm/gems/ree-1.8.7-2011.03@app/bundler/gems/compass-91a748a91636/lib/compass/app_integration/rails/actionpack31/railtie.rb:47
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/initializable.rb:25:in `instance_exec'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/initializable.rb:25:in `run'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/initializable.rb:50:in `run_initializers'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/initializable.rb:49:in `each'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/initializable.rb:49:in `run_initializers'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/application.rb:92:in `initialize!'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/railtie/configurable.rb:30:in `send'
~/.rvm/gems/ree-1.8.7-2011.03@app/gems/railties-3.1.0.rc5/lib/rails/railtie/configurable.rb:30:in `method_missing'
~/sites/user/app/config/environment.rb:5
~/sites/user/app/config.ru:3:in `require'
~/sites/user/app/config.ru:3
~/Library/Application Support/Pow/Versions/0.3.1/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.3.1/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/sites/user/app/config.ru:1:in `new'
~/sites/user/app/config.ru:1
```

And part of the Gemfile for reference

```
gem "haml", "~> 3.1.1"
gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'compass', :git => 'https://github.com/chriseppstein/compass.git', :branch => 'rails31'
gem "compass-960-plugin", "~> 0.10", :require => 'ninesixty'
gem 'jquery-rails', '>= 1.0'
gem 'formtastic', '~>1.1.0'
```

I didn't get this error until I changed the Compass gem.

Thanks!

**Comment by scottdavis** [comment]
sass-rails broke with the sprockets update

**Comment by natebird** [comment]
Good to know. Anything I can do? Or just wait for sass-rails to pick up a fixed version of sprockets?

**Comment by natebird** [comment]
Changing the Gemfile to use `gem 'sass-rails'` worked.
