### ISSUE TITLE
marshal data

### ISSUE THREAD

**Issue by vladaruz** [Compass/compass#5]
Everytime I try to create a new project I get this 
"ArgumentError on line 18 of C: marshal data too short"

**Comment by chriseppstein** [comment]
Please double check that you are running the latest version of haml. If it still happens, please post the full stack trace

**Comment by vladaruz** [comment]
Here's what I get.

```
C:\>haml -v
Haml 2.0.9

C:\>compass -f blueprint sample-project --trace
directory sample-project/
directory images/
directory src/
directory stylesheets/
   create config.rb
   create screen.sass
   create print.sass
   create ie.sass
   create grid.png
   exists stylesheets
  compile ie.sass
ArgumentError on line 18 of C: marshal data too short
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/files.rb:18:in `tree_for'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/file_node.rb:19:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:73:in `_perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:61:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `map'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/file_node.rb:20:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:73:in `_perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:61:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `map'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/file_node.rb:20:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:73:in `_perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:61:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `map'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/file_node.rb:20:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:73:in `_perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:61:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `map'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:82:in `perform_children'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:78:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:73:in `_perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:61:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/tree/node.rb:39:in `render'
  C:/Ruby/lib/ruby/gems/1.8/gems/haml-edge-2.1.8/lib/sass/engine.rb:108:in `render'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/actions.rb:68:in `compile'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/compiler.rb:37:in `run'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/compiler.rb:36:in `each'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/compiler.rb:36:in `run'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/commands/update_project.rb:19:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/commands/stamp_pattern.rb:19:in `perform'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/commands/base.rb:15:in `execute'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/commands/project_base.rb:19:in `execute'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/exec.rb:197:in `do_command'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/exec.rb:57:in `perform!'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/lib/compass/exec.rb:40:in `run!'
  C:/Ruby/lib/ruby/gems/1.8/gems/chriseppstein-compass-0.6.6/bin/compass:8
  C:/Ruby/bin/compass:19:in `load'
  C:/Ruby/bin/compass:19
```

**Comment by chriseppstein** [comment]
Compass requires edge haml (version > 2.1). You can install it from source, or using the "haml-edge" gem. Instructions are on the wiki.
