### ISSUE TITLE
Compilation failed with the --config option

### ISSUE THREAD

**Issue by piouPiouM** [Compass/compass#51]
Stack trace:

```
$ compass --config=src/sass.rb --trace my_project
NameError on line 68 of /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/project_base.rb: undefined local variable or method `file' for #<Compass::Commands::CreateProject:0x5a3c00>
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/project_base.rb:52:in `read_project_configuration'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/installer_command.rb:9:in `configure!'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/commands/project_base.rb:18:in `execute'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:242:in `do_command'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:57:in `perform!'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/lib/compass/exec.rb:40:in `run!'
  /Library/Ruby/Gems/1.8/gems/chriseppstein-compass-0.8.17/bin/compass:8
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
```

**Comment by piouPiouM** [comment]
I close this issue, it's not a bug.
config option is used to load a file and not create one… I'm stupid >_>
