### ISSUE TITLE
"rake examples" not working for me

### ISSUE THREAD

**Issue by carljm** [Compass/compass#54]
On edge compass, if I follow the instructions in examples/README and run "rake examples" at project root, I get an error "wrong number of arguments (0 for 1)", here's the full traceback with --trace

```
carljm@kale:~/projects/compass/compass$ rake examples --trace
(in /home/carljm/projects/compass/compass)
rake aborted!
wrong number of arguments (0 for 1)
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:31:in `index'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:31:in `register'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:60:in `register_directory'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:46:in `discover'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:45:in `each'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:45:in `discover'
/home/carljm/projects/compass/compass/lib/compass/frameworks.rb:92
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/home/carljm/projects/compass/compass/lib/compass.rb:21
/home/carljm/projects/compass/compass/lib/compass.rb:20:in `each'
/home/carljm/projects/compass/compass/lib/compass.rb:20
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/home/carljm/projects/compass/compass/Rakefile:16
/usr/lib/ruby/1.8/rake.rb:2149:in `load'
/usr/lib/ruby/1.8/rake.rb:2149:in `raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1897:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1948:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1896:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:1880:in `run'
/usr/lib/ruby/1.8/rake.rb:1948:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1878:in `run'
/usr/bin/rake:28
```

Quite likely this is just because I have a crazy-out-of-date rake; I'm not a Ruby dev and don't really ever use it. Thought it was worth reporting anyway.

```
carljm@kale:~/projects/compass/compass$ rake --version
rake, version 0.8.1
```

**Comment by chriseppstein** [comment]
What version of compass?

**Comment by carljm** [comment]
Well, I have compass 0.8.17 installed globally, but from the traceback it appears to be using the git checkout I'm in, not the global gem. The checkout is from here http://github.com/ericam/compass/tree/edge (testing Eric's Susy example); based on a checkout of your edge as of this morning.

**Comment by chriseppstein** [comment]
Eek. the issue is that I'm using a form of Array#index that only exists in ruby 1.8.7+

**Comment by chriseppstein** [comment]
I pushed a change to my edge branch
