### ISSUE TITLE
Rails.root is nil! on require sass/plugin in watch_project on rake tasks

### ISSUE THREAD

**Issue by rockrep** [Compass/compass#824]
We upgraded our Rails 3.1.3 app from Ruby 1.9.2-p290 to Ruby 1.9.3-p125 and rake commands and the rails console all fail with error:
.../sass-3.1.15/lib/sass/util.rb:332:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)

Stacktrace and bundle install output available here:  https://gist.github.com/2287791

If we comment out lib/compass/commands/watch_project.rb:5, then rake tasks and rails console execute successfully.

Thanks,
-Michael

**Comment by chriseppstein** [comment]
you need to add compass rails into your project https://github.com/Compass/compass-rails

**Comment by rockrep** [comment]
ah.  Thanks Chris.  All better now

**Comment by ram-ai-kumar** [comment]
Not fixed for me, even after using compass-rails

ruby 1.9.2p318 (2012-02-14 revision 34678) [x86_64-darwin10.8.0]
gem -v 1.8.20
rvm 1.11.0-pre (stable)

**Comment by alexmarles** [comment]
Not fixed for me neither and I'm using compass-rails too, but rbenv instead of rvm:

ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.3.0]
gem -v 1.8.10

**Comment by scottdavis** [comment]
post your gemfiles

**Comment by ram-ai-kumar** [comment]
```
source 'http://rubygems.org'

gem 'rails', '3.2.2'
gem 'mysql2'

 # Gems used only for assets and not required
 # in production environments by default.
group :assets do
  gem 'compass-rails'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'bcrypt-ruby', '~> 3.0.0' # To use ActiveModel has_secure_password
gem 'chronic'
gem 'devise'
gem 'jquery-rails', '1.0.16'
gem 'twitter-bootstrap-rails'

group :development, :test do
  gem 'ruby-debug19', :require => 'ruby-debug'

  gem 'capistrano'
  gem 'capistrano_colors'

  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-coffeescript'
  gem 'guard-compass'
  gem 'guard-cucumber'
  gem 'guard-migrate'
  gem 'guard-rails'
  gem 'guard-rails-assets'
  gem 'guard-rspec'
end

group :test do
  gem 'cucumber-rails'
  gem "rspec-rails"
  gem "capybara"
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'launchy'
  gem 'watir-webdriver'
  gem 'timecop'
end
```

**Comment by scottdavis** [comment]
Try swapping compass-rails and sass-rails

**Comment by alexmarles** [comment]
``` ruby
  1 source 'http://rubygems.org'                                                    
  2                                                                                 
  3 gem 'rails', '3.2.2'                                                            
  4                                                                                 
  5 gem 'pg'                                                                        
  6                                                                                 
  7 gem 'slim'                                                                      
  8 gem 'jquery-rails'                                                              
  9 gem 'passenger'                                                                 
 10                                                                                 
 11 gem 'simple_form'                                                               
 12 gem 'carrierwave'                                                               
 13 gem 'rmagick'                                                                   
 14 gem 'mail_form'                                                                 
 15 gem 'simple-navigation'                                                         
 16 gem 'will_paginate'                                                             
 17 gem 'cells'                                                                     
 18 gem 'globalize3'                                                                
 19 gem 'translate_routes'                                                          
 20 gem 'fog'                                                                       
 21                                                                                 
 22 gem 'devise'                                                                    
 23                                                                                 
 24 gem 'inherited_resources'                                                       
 25                                                                                 
 26 gem 'markdownizer'                                                              
 27 gem 'therubyracer'                                                              
 28 gem 'taps'                                                                      
 29                                                                                 
 30 group :assets do                                                                
 31   gem 'sass-rails', " ~> 3.2.3"                                                 
 32   gem 'compass-rails'                                                           
 33   gem 'coffee-rails', " ~> 3.2.1"                                               
 34   gem 'uglifier'                                                                
 35 end                                                                             
 36                                                                                 
 37                                                                                 
 38 group :test, :development do                                                    
 39   gem 'guard-compass'                                                           
 40   gem 'guard-passenger'                                                         
 41   gem 'cucumber-rails'                                                          
 42   gem 'rspec-rails'                                                             
 43   gem 'spork'                                                                   
 44   gem 'guard-spork'                                                             
 45   gem 'guard-rspec'                                                             
 46   gem 'guard-cucumber'                                                          
 47   gem 'launchy'                                                                 
 48   gem 'database_cleaner'                                                        
 49   gem 'sqlite3'                                                                 
 50 end
```

Using Mac OSX Lion, no problem with it in Ubuntu

**Comment by ram-ai-kumar** [comment]
swapping does not work !

```

  gem 'sass-rails',   '~> 3.2.3'
  gem 'compass-rails'
```

**Comment by ram-ai-kumar** [comment]
My mistake in ignoring the entire error message

```
WARNING: Cucumber-rails required outside of env.rb.  The rest of loading is being defered until env.rb is called.
  To avoid this warning, move 'gem cucumber-rails' under only group :test in your Gemfile
/Users/ram/.rvm/gems/ruby-1.9.2-p318@abalone/gems/sass-3.1.10/lib/sass/util.rb:319:in `rails_root': ERROR: Rails.root is nil! (RuntimeError)
```

resolution: I re-arranged the groups in gemfile.
also found this stackoverflow thread later.
http://stackoverflow.com/questions/9781456/cucumber-rails-required-outside-of-env-rb-the-rest-of-loading-is-being-defered

Thank you everyone for your time & effort.

**Comment by alexmarles** [comment]
Thank you very much! That's my solution too!

**Comment by scottdavis** [comment]
so is it safe to close this?

**Comment by ram-ai-kumar** [comment]
development environment worked after switching groups. guard still failed with same error.
I had to comment out 'guard-compass' to get it running correctly.

Can close. Good from me.
Cannot say about others here. Everyone has contributed efforts. Thanks to everyone.

**Comment by skamansam** [comment]
What did you move your groups to? Did you move them around in the file, or did you move your gems between the groups? Could you please post your working Gemfile?

**Comment by acarvajal09** [comment]
what happend in here? any solution?
