### ISSUE TITLE
Rails 3 support

### ISSUE THREAD

**Issue by slbug** [Compass/compass#84]
full description and temporary fix here - http://groups.google.com/group/compass-users/browse_thread/thread/45a07c67f665e802

**Comment by merbjedi** [comment]
After adding compass (git master) to my Rails 3 project, it started blowing up. Turns out compass was setting Sass::Plugin.options[:cache_location] to nil.

Easy workaround, just edit your config/initializers/compass.rb and explicitly set your :cache_location after the configure_sass_plugin! call. Here's what I did

```
# ... other stuff before this .....
Compass.configure_sass_plugin!

# added to make sure sass has the sass-cache directory
FileUtils.mkdir_p Rails.root.join("tmp", "sass-cache").to_s
Sass::Plugin.options[:cache_location] ||= Rails.root.join("tmp", "sass-cache").to_s
```

Here's the backtrace

```
/*
TypeError: can't convert nil into String

Backtrace:
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/files.rb:88:in `join'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/files.rb:88:in `sassc_filename'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/files.rb:24:in `tree_for'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:330:in `update_stylesheet'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:225:in `update_stylesheets'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:216:in `each'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:216:in `update_stylesheets'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:214:in `each'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:214:in `update_stylesheets'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin.rb:190:in `check_for_updates'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/haml-edge-2.3.151/lib/sass/plugin/rack.rb:43:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/head.rb:14:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/methodoverride.rb:24:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/params_parser.rb:20:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/flash.rb:167:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/session/cookie_store.rb:107:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/cookies.rb:205:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/callbacks.rb:46:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/activesupport/lib/active_support/callbacks.rb:409:in `_run_call_callbacks'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/activesupport/lib/active_support/callbacks.rb:88:in `send'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/activesupport/lib/active_support/callbacks.rb:88:in `run_callbacks'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/callbacks.rb:44:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:62:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/rack/logger.rb:13:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/runtime.rb:17:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/lock.rb:11:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/lock.rb:11:in `synchronize'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/lock.rb:11:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/actionpack/lib/action_dispatch/middleware/static.rb:30:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/application.rb:95:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/application.rb:41:in `send'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/application.rb:41:in `method_missing'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/rack/debugger.rb:21:in `call'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/rack/log_tailer.rb:15:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/content_length.rb:13:in `call'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/handler/webrick.rb:48:in `service'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:162:in `start'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:95:in `start'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:92:in `each'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:92:in `start'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:23:in `start'
/Users/jc/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/1.8/webrick/server.rb:82:in `start'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/handler/webrick.rb:14:in `run'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/server.rb:155:in `start'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/commands/server.rb:50:in `start'
/Users/jc/.rvm/gems/ruby-1.8.7-p249%rails3/gems/rack-1.1.0/lib/rack/server.rb:83:in `start'
/Users/jc/.bundle/bundler/gems/rails-017fcbec3ff7c4edd81212b16c3f2690d8f18efb-master/railties/lib/rails/commands.rb:39
script/rails:10:in `require'
script/rails:10
```

**Comment by chriseppstein** [comment]
fixed in .pre6
