### ISSUE TITLE
sprite-dimensions doesn't work when you have a different sprite path

### ISSUE THREAD

**Issue by pheld** [Compass/compass#884]
Using the latest stable branch, compass throws when trying to use `sprite-dimensions` if I use the sprite path app/assets/sprites instead of app/assets/images

```
can't convert nil into String

/bundler/gems/compass-105087721e1a/lib/compass/sass_extensions/functions/image_size.rb:17:in `extname'
/bundler/gems/compass-105087721e1a/lib/compass/sass_extensions/functions/image_size.rb:17:in `initialize'
/bundler/gems/compass-105087721e1a/lib/compass/sass_extensions/functions/image_size.rb:50:in `new'
/bundler/gems/compass-105087721e1a/lib/compass/sass_extensions/functions/image_size.rb:50:in `image_dimensions'
/bundler/gems/compass-105087721e1a/lib/compass/sass_extensions/functions/image_size.rb:10:in `image_height'
/gems/sass-3.1.17/lib/sass/script/funcall.rb:88:in `_perform'
/gems/sass-3.1.17/lib/sass/script/node.rb:40:in `perform'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:216:in `visit_prop'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block (2 levels) in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:125:in `visit_if'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block (2 levels) in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block (2 levels) in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `block in visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:201:in `visit_mixin'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:238:in `visit_rule'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:146:in `visit_import'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `map'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
/gems/sass-3.1.17/lib/sass/tree/visitors/base.rb:37:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:18:in `visit'
/gems/sass-3.1.17/lib/sass/tree/visitors/perform.rb:7:in `visit'
/gems/sass-3.1.17/lib/sass/tree/root_node.rb:20:in `render'
/gems/sass-3.1.17/lib/sass/engine.rb:299:in `_render'
/gems/sass-3.1.17/lib/sass/engine.rb:246:in `render'
/gems/sass-rails-3.2.5/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/gems/sprockets-2.1.2/lib/sprockets/context.rb:177:in `block in evaluate'
/gems/sprockets-2.1.2/lib/sprockets/context.rb:174:in `each'
/gems/sprockets-2.1.2/lib/sprockets/context.rb:174:in `evaluate'
/gems/sprockets-2.1.2/lib/sprockets/processed_asset.rb:12:in `initialize'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `new'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:241:in `block in build_asset'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:262:in `circular_call_protection'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:240:in `build_asset'
/gems/sprockets-2.1.2/lib/sprockets/index.rb:89:in `block in build_asset'
/gems/sprockets-2.1.2/lib/sprockets/caching.rb:19:in `cache_asset'
/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
/gems/sprockets-2.1.2/lib/sprockets/bundled_asset.rb:38:in `init_with'
/gems/sprockets-2.1.2/lib/sprockets/asset.rb:24:in `from_hash'
/gems/sprockets-2.1.2/lib/sprockets/caching.rb:15:in `cache_asset'
/gems/sprockets-2.1.2/lib/sprockets/index.rb:88:in `build_asset'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:163:in `find_asset'
/gems/sprockets-2.1.2/lib/sprockets/index.rb:56:in `find_asset'
/gems/sprockets-2.1.2/lib/sprockets/environment.rb:74:in `find_asset'
/gems/sprockets-2.1.2/lib/sprockets/base.rb:171:in `[]'
/gems/actionpack-3.2.3/lib/sprockets/helpers/rails_helper.rb:126:in `asset_for'
/gems/actionpack-3.2.3/lib/sprockets/helpers/rails_helper.rb:44:in `block in stylesheet_link_tag'
/gems/actionpack-3.2.3/lib/sprockets/helpers/rails_helper.rb:43:in `collect'
/gems/actionpack-3.2.3/lib/sprockets/helpers/rails_helper.rb:43:in `stylesheet_link_tag'
/gems/actionpack-3.2.3/lib/action_view/template.rb:143:in `block in render'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:125:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/template.rb:141:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `block in instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:18:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:36:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:17:in `render'
/gems/actionpack-3.2.3/lib/action_view/helpers/rendering_helper.rb:24:in `render'
/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/gems/haml-3.1.4/lib/haml/helpers.rb:90:in `non_haml'
/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
/gems/actionpack-3.2.3/lib/action_view/template.rb:143:in `block in render'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:125:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/template.rb:141:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `block in instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:18:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:36:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:17:in `render'
/gems/actionpack-3.2.3/lib/action_view/helpers/rendering_helper.rb:24:in `render'
/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:11:in `block in render_with_haml'
/gems/haml-3.1.4/lib/haml/helpers.rb:90:in `non_haml'
/gems/haml-3.1.4/lib/haml/helpers/action_view_mods.rb:11:in `render_with_haml'
/gems/actionpack-3.2.3/lib/action_view/template.rb:143:in `block in render'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:125:in `instrument'
/gems/actionpack-3.2.3/lib/action_view/template.rb:141:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/template_renderer.rb:18:in `render'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:36:in `render_template'
/gems/actionpack-3.2.3/lib/action_view/renderer/renderer.rb:17:in `render'
/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:110:in `_render_template'
/gems/actionpack-3.2.3/lib/action_controller/metal/streaming.rb:225:in `_render_template'
/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:103:in `render_to_body'
/gems/actionpack-3.2.3/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
/gems/actionpack-3.2.3/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:88:in `render'
/gems/actionpack-3.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
/gems/activesupport-3.2.3/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/Users/peter/.rvm/rubies/ruby-1.9.3-p125-perf/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/gems/activesupport-3.2.3/lib/active_support/core_ext/benchmark.rb:5:in `ms'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
/gems/activerecord-3.2.3/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
/gems/sunspot_rails-2.0.0.pre.111215/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:39:in `render'
/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/gems/actionpack-3.2.3/lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
/gems/actionpack-3.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:167:in `process_action'
/gems/actionpack-3.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:592:in `block (2 levels) in _run__4502270899854176699__process_action__4401199106072678201__callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1171'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1171'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:547:in `block in _run__4502270899854176699__process_action__4401199106072678201__callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1170'
/gems/vanity-1.8.0/lib/vanity/frameworks/rails.rb:104:in `vanity_context_filter'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1170'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:491:in `_run__4502270899854176699__process_action__4401199106072678201__callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
/gems/actionpack-3.2.3/lib/abstract_controller/callbacks.rb:17:in `process_action'
/gems/actionpack-3.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `block in instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/gems/activesupport-3.2.3/lib/active_support/notifications.rb:123:in `instrument'
/gems/actionpack-3.2.3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/gems/actionpack-3.2.3/lib/action_controller/metal/params_wrapper.rb:205:in `process_action'
/gems/activerecord-3.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/bundler/gems/query_reviewer-9de60e75d180/lib/query_reviewer/controller_extensions.rb:53:in `perform_action_with_query_review'
/gems/actionpack-3.2.3/lib/abstract_controller/base.rb:121:in `process'
/gems/actionpack-3.2.3/lib/abstract_controller/rendering.rb:45:in `process'
/bundler/gems/query_reviewer-9de60e75d180/lib/query_reviewer/controller_extensions.rb:62:in `process_with_query_review'
/gems/actionpack-3.2.3/lib/action_controller/metal.rb:203:in `dispatch'
/gems/actionpack-3.2.3/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/gems/actionpack-3.2.3/lib/action_controller/metal.rb:246:in `block in action'
/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:36:in `call'
/gems/journey-1.0.3/lib/journey/router.rb:68:in `block in call'
/gems/journey-1.0.3/lib/journey/router.rb:56:in `each'
/gems/journey-1.0.3/lib/journey/router.rb:56:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/routing/route_set.rb:600:in `call'
/bundler/gems/bullet-65aed6afa382/lib/bullet/rack.rb:11:in `call'
/gems/airbrake-3.0.5/lib/airbrake/rack.rb:27:in `call'
/gems/sass-3.1.17/lib/sass/plugin/rack.rb:54:in `call'
/gems/warden-1.0.5/lib/warden/manager.rb:35:in `block in call'
/gems/warden-1.0.5/lib/warden/manager.rb:34:in `catch'
/gems/warden-1.0.5/lib/warden/manager.rb:34:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
/gems/rack-1.4.1/lib/rack/etag.rb:23:in `call'
/gems/rack-1.4.1/lib/rack/conditionalget.rb:25:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/head.rb:14:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/flash.rb:242:in `call'
/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:205:in `context'
/gems/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/cookies.rb:338:in `call'
/gems/activerecord-3.2.3/lib/active_record/query_cache.rb:64:in `call'
/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `_run__1067314560940659948__call__3715150321729048339__callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:405:in `__run_callback'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
/gems/activesupport-3.2.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/reloader.rb:65:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/gems/railties-3.2.3/lib/rails/rack/logger.rb:26:in `call_app'
/gems/railties-3.2.3/lib/rails/rack/logger.rb:16:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/request_id.rb:22:in `call'
/gems/rack-1.4.1/lib/rack/methodoverride.rb:21:in `call'
/gems/rack-1.4.1/lib/rack/runtime.rb:17:in `call'
/gems/rack-1.4.1/lib/rack/lock.rb:15:in `call'
/gems/actionpack-3.2.3/lib/action_dispatch/middleware/static.rb:62:in `call'
/gems/airbrake-3.0.5/lib/airbrake/user_informer.rb:12:in `call'
/gems/railties-3.2.3/lib/rails/engine.rb:479:in `call'
/gems/railties-3.2.3/lib/rails/application.rb:220:in `call'
/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `method_missing'
```

**Comment by pheld** [comment]
this was fixed by making the sprite_load_path include ./: `sprite_load_path = ['./app/assets/sprites']` works but `sprite_load_path = ['app/assets/sprites']` does not. Maybe consider this closed and/or update docs?

**Comment by scottdavis** [comment]
as a rule of thumb i always expand my paths then setting up sprite load paths so theres no guessing on rubys part
