### ISSUE TITLE
Pathname support

### ISSUE THREAD

**Issue by merbjedi** [Compass/compass#92]
Compass should be smart about handle Rails3 Pathnames. For example, Rails.root now returns a Pathname object instead of a string. This wreaks havok with Compass master 

Patch coming...

**Comment by chriseppstein** [comment]
great!

**Comment by merbjedi** [comment]
Add a project configuration file like so:

```
Compass.add_project_configuration(Rails.root.join("config", "compass.rb"))
```

Produces this error message:

```
/Users/jc/Gems/compass/lib/compass/configuration/data.rb:33:in `initialize': I need a name! (RuntimeError)
    from /Users/jc/Gems/compass/lib/compass/configuration/serialization.rb:18:in `new'
    from /Users/jc/Gems/compass/lib/compass/configuration/serialization.rb:18:in `new_from_string'
    from /Users/jc/Gems/compass/lib/compass/configuration/helpers.rb:34:in `configuration_for'
    from /Users/jc/Gems/compass/lib/compass/configuration/helpers.rb:75:in `add_project_configuration'
```

Updating Configuration::Data so it supports Pathname (since pathname responds to .read)

**Comment by merbjedi** [comment]
fixed via http://github.com/merbjedi/compass/commit/2b985fd191b02aface72e52111d0ad818e73ad78

**Comment by merbjedi** [comment]
Also in my compass.rb config, if I have this line:

```
project_path = Rails.root
```

I get this error:

```
(eval):4:in `project_path': undefined method `=~' for #<Pathname:/Users/jc/Rails3/whitelabel_jobs> (NoMethodError)
    from /Users/jc/Gems/compass/lib/compass/configuration/defaults.rb:46:in `default_sass_path'
    from /Users/jc/Gems/compass/lib/compass/configuration/inheritance.rb:132:in `method_missing'
    from /Users/jc/Gems/compass/lib/compass/configuration/inheritance.rb:132:in `method_missing'
    from /Users/jc/Gems/compass/lib/compass/configuration/inheritance.rb:105:in `default_for'
    from /Users/jc/Gems/compass/lib/compass/configuration/inheritance.rb:126:in `read'
    from /Users/jc/Gems/compass/lib/compass/configuration/inheritance.rb:53:in `sass_path'
    from (eval):3:in `sass_path'
```

**Comment by merbjedi** [comment]
This should solve the issue with Pathnames inside of compass configs:
http://github.com/merbjedi/compass/commit/5fc52baa0257f9b0ae12e3d186ecd2c4842e816d

**Comment by chriseppstein** [comment]
merged. thanks!
