### ISSUE TITLE
image-url() causes "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by danielres** [Compass/compass#979]
In a sass file, this works:

```
body
  +background(linear-gradient(top, lighten($c,30%), darken($c,0%) 700px))
```

This does not:

```
body
  +background(image-url("textured_stripes.png"), linear-gradient(top, lighten($c,30%), darken($c,0%) 700px))
```

I'm using compass with `bundle exec compass watch`

It was working fine a few days ago, before upgrading my PC to the last ubuntu.
After reinstalling everything (rvm, ruby, bundler,...), and going back to this app,  I get this error.

Here is the stack trace:

```
NoMethodError on line ["32"] of /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-rails-3.2.5/lib/sass/rails/helpers.rb: undefined method `[]' for nil:NilClass
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-rails-3.2.5/lib/sass/rails/helpers.rb:25:in `image_url'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/script/funcall.rb:88:in `_perform'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/script/node.rb:40:in `perform'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:191:in `block in visit_mixin'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:187:in `each'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:187:in `inject'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:187:in `visit_mixin'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `map'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:238:in `visit_rule'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:146:in `block in visit_import'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:146:in `map'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:146:in `visit_import'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `map'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:53:in `visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `block in visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/base.rb:37:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:18:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/visitors/perform.rb:7:in `visit'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/tree/root_node.rb:20:in `render'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/engine.rb:300:in `_render'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/sass-3.1.20/lib/sass/engine.rb:247:in `render'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:140:in `block (2 levels) in compile'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:126:in `timed'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:139:in `block in compile'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/logger.rb:45:in `red'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:138:in `compile'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:118:in `compile_if_required'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:103:in `block (2 levels) in run'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:101:in `each'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:101:in `block in run'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:126:in `timed'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/compiler.rb:100:in `run'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/commands/update_project.rb:45:in `perform'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/commands/base.rb:18:in `execute'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/commands/project_base.rb:19:in `execute'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/bin/compass:30:in `block in <top (required)>'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/bin/compass:44:in `call'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/gems/compass-0.12.2/bin/compass:44:in `<top (required)>'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/bin/compass:19:in `load'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/bin/compass:19:in `<main>'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
  /home/daniel/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```

Any idea ?
Thanks

**Comment by chriseppstein** [comment]
[sass-rails](https://github.com/rails/sass-rails/) implements a rails-specific version of `image-url`. Can you file this bug over there?
