### ISSUE TITLE
Undefined Method [] for Float

### ISSUE THREAD

**Issue by Snugug** [Compass/compass#994]
I've set an `em` value as a float (because `em`s are allowed to be floats) and Compass is spitting back an error from config.rb.This may be a Sass issue, but because the error is spitting out from config.rb, I thought maybe not and filing it here. Here's my full backtrace.

``` bash

NoMethodError on line 44 of /Users/Magrathea/Development/breakpoint/test/config.rb: undefined method `[]' for 41.1:Float
  /Users/Magrathea/Development/breakpoint/test/config.rb:43:in `each'
  /Users/Magrathea/Development/breakpoint/test/config.rb:43:in `featureExists'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/script/funcall.rb:106:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/script/funcall.rb:106:in `_perform'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/script/node.rb:40:in `perform'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:323:in `visit_variable'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:203:in `visit_if'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:159:in `visit_each'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:159:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:159:in `visit_each'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:157:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:157:in `visit_each'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:156:in `visit_each'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:203:in `visit_if'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:264:in `visit_mixin'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:264:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:264:in `visit_mixin'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:264:in `visit_mixin'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:68:in `perform_arguments'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:259:in `visit_mixin'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:316:in `visit_rule'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:224:in `visit_import'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `map'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:53:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:107:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:119:in `with_environment'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:106:in `visit_children'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:126:in `visit_root'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/base.rb:37:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:98:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:7:in `send'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/visitors/perform.rb:7:in `visit'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/tree/root_node.rb:20:in `render'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/engine.rb:315:in `_render'
  /usr/local/gems/sass-3.2.1/lib/sass/../sass/engine.rb:262:in `render'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:140:in `compile'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:139:in `compile'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/logger.rb:45:in `red'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:138:in `compile'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:118:in `compile_if_required'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:103:in `run'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `each'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:101:in `run'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:126:in `timed'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/compiler.rb:100:in `run'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/commands/update_project.rb:45:in `perform'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/commands/base.rb:18:in `execute'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/commands/project_base.rb:19:in `execute'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /usr/local/gems/compass-0.13.alpha.0/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/local/gems/compass-0.13.alpha.0/bin/compass:29
  /usr/local/gems/compass-0.13.alpha.0/bin/compass:43:in `call'
  /usr/local/gems/compass-0.13.alpha.0/bin/compass:43
  /usr/bin/compass:19:in `load'
  /usr/bin/compass:19
```

I'm doing some simple `em` conversion when this is called. Upon a little bit of inspection, it seems as if no numbers with units work with floats, including percentages, px, and pt.

**Comment by chriseppstein** [comment]
This is an error in your custom function, not sass or compass.

/Users/Magrathea/Development/breakpoint/test/config.rb on line 43.

Happy to help you debug it, but this is not a bug.

**Comment by Snugug** [comment]
Hmm, interesting. I'll 2x check it.
